### ISSUE TITLE
G2 不开源么？

### ISSUE THREAD

**Issue by afc163** [antvis/feedback#1]
先把大家最关心的问题给问了。:santa:

**Comment by simaQ** [comment]
我们是很愿意开源的，但是呢，由于各种原因，G2 目前的开源工作还没有完全准备好，暂时先外开放。

**Comment by haibinyu** [comment]
期待开源的那一刻，:beer:

**Comment by HuarenYu** [comment]
@haibinyu 使用的话需要商业授权吗？

**Comment by haibinyu** [comment]
@HuarenYu ，这个得问官方人士， @afc163 @simaQ .
个人认为是不需要的。

**Comment by simaQ** [comment]
@HuarenYu  这个不需要的哦~

**Comment by dxq613** [comment]
不需要商业授权

**Comment by dxq613** [comment]
不需要商业授权，可以直接使用

**Comment by lyuehh** [comment]
你们自己人还问开不开源。。 抢沙发不厚道。。

**Comment by kaiailu** [comment]
@lyuehh 他是来捣乱的。。。

**Comment by lyuehh** [comment]
@kaiailu  看出来了。。

**Comment by lifesinger** [comment]
因为专利的问题，目前公司不允许开源，因此这次是开放，而不是开源。大家可以先用起来，有任何诉求（除了开放源码），可以这里讨论。

**Comment by plandem** [comment]
so can it be used at commercial software? You need to clarify license model - MIT, GPL or what?!

**Comment by cchlei** [comment]
希望开源啊

**Comment by plandem** [comment]
can i help somehow?! :) i would like to use it :)

**Comment by simaQ** [comment]
yep, you can use it directly without any commercial license. @plandem

**Comment by iwege** [comment]
@lifesinger 所以现在目前只能用，遇到问题的话需要反馈给你们做修改么？

**Comment by simaQ** [comment]
@iwege 欢迎使用并反馈问题，我们会及时跟进的。

**Comment by reverland** [comment]
看到repo里的GPL协议，手抖加进去的么。。。

**Comment by nuintun** [comment]
不开源的话表示持观望态度~

**Comment by leungwensen** [comment]
已经开源啦，欢迎使用～～  https://github.com/antvis/g2
