### ISSUE TITLE
分组柱状图json数据问题

### ISSUE THREAD

**Issue by jobnicer** [antvis/feedback#10]
http://g2.alipay.com/demo/04-column/column-dodge.html 里的图表所用的json数据仅仅给了个链接/data.json?filename=diamond，麻烦你贴出来，方便学习。

**Comment by simaQ** [comment]
😄  你好，这个数据是一份钻石数据，可以通过这个链接获取：

https://github.com/antvis/antvis.github.io/blob/master/diamond.json

**Comment by dxq613** [comment]
数据已经全部上传到：https://github.com/antvis/resource

**Comment by jobnicer** [comment]
谢谢。

**Comment by jobnicer** [comment]
谢谢 @simaQ @dxq613
