### ISSUE TITLE
在dva框架中如何使用g2

### ISSUE THREAD

**Issue by sevennights** [antvis/feedback#100]
如果是 G2 的使用问题，请您按照下面的模板来提 issue，并打上 label，真心感谢~~~

## 我的需求/我的问题
在dva框架中如何使用g2
## 数据以及出现问题的源代码

在dva框架中取不到ID

## G2 的版本以及使用环境

- G2 版本： 2.2.0
- 使用环境： Mac OS X, Chrome

**Comment by simaQ** [comment]
@jaredleechn  能帮忙解答么？

**Comment by jaredleechn** [comment]
可以使用 https://github.com/antvis/g2-react

也可以参考代码自己封装一个

**Comment by sevennights** [comment]
好的 谢谢 @simaQ @jaredleechn 我研究下
