### ISSUE TITLE
研究G2，显示某地市地图未能实现！

### ISSUE THREAD

**Issue by zhangjian171110** [antvis/feedback#101]
如果是其他的问题，请按照如下模板来提 issue,并打上 label，真心感谢~~~

## 我的问题
  
非常感谢蚂蚁金服-体验技术部-数据图形组的辛苦成果，最近一直在研究G2，遇到初始化某个地市（包含县区）的地图，且展示热力图，查阅、仔细阅读手册、API，未能实现。

## 我的期望
希望能提供某个地市的地图json，或者ChinaGeoJSON["某某city"]，非常感谢！

**Comment by simaQ** [comment]
市级的 geojson 数据比较难获取，G2 是支持的，只要你有这个 geojson 的数据。

**Comment by zhangjian171110** [comment]
@simaQ ;试图自定义geojson的数据
             {
			"type": "Feature",
			"id": "地市某区域行政区划",
			"properties": {
				"name": "区县名",
				"cp": [
					具体经纬度
				],
				"childNum": “”			},
			"geometry": {
				"type": "Polygon",
				"coordinates": [
                                  ]
上述Json模板：
   能帮忙解释下  childNum   与  coordinates（很多经纬度）什么意思吗？

**Comment by simaQ** [comment]
childNum 这个属性不需要太关注，coordinates 就是用来存储经纬度坐标的，但是对于不同的几何体结构会有所区别，你可以参考这个文档： http://www.oschina.net/translate/geojson-spec#geometry-objects

**Comment by zhangjian171110** [comment]
@simaQ  ，非常感谢，现已经实现！
