### ISSUE TITLE
饼图的label如何设置自定义html

### ISSUE THREAD

**Issue by SlimJason** [antvis/feedback#102]
如果是 G2 的使用问题，请您按照下面的模板来提 issue，并打上 label，真心感谢~~~

## 我的需求/我的问题
饼图的label如何设置自定义html
## 数据以及出现问题的源代码
var dataSource = [
	        {name: '峰时', value: BillUtils.formatFloat(data.peekRadio*100,0), num:data.peekQ},
	        {name: '谷时', value: BillUtils.formatFloat(data.valleyRadio*100,0), num:data.valleyQ}
	      ];
	      var Stat = G2.Stat;
	      var g2PvChart = new G2.Chart({
	        id: 'g2_pv_chart',
	        forceFit:true,
	        height: clientRadio>1?170*clientRadio:170,
	        plotCfg: {
				margin: [35, 15, 10, 15],
			}
	      });
	      g2PvChart.source(dataSource);
	      // 重要：绘制饼图时，必须声明 theta 坐标系
	      g2PvChart.coord('theta', {
	        radius: 1,
	        inner:0.6
	      });
	      g2PvChart.tooltip({
	        title: null,
	        map: {
	          value: 'value'
	        }
	      });
	      g2PvChart.legend(false);
	      g2PvChart.intervalStack()
	        .position(Stat.summary.percent('value'))
	        .color('name',['#FF6242', '#FFD02D'])
	        .label('name*..percent',function(name, percent){
	        	var label = "";
	        	if(name == '峰时'){
	        		label = name+' '+data.peekQ+' 度';
	        	}else if(name == '谷时'){
	        		label = name+' '+data.valleyQ+' 度';
	        	}
	        	return label;
	      });
	      g2PvChart.render();
	      window.addEventListener("resize", function() {
	      	var _clientRadio = document.documentElement.clientWidth/375;
			if(clientRadio > 1){
				$chartBody.find(".chart").height(1.77*_clientRadio+'rem');
				g2PvChart.changeSize(351*_clientRadio, 170*_clientRadio).forceFit();;
			}else{
				$chartBody.find(".chart").height("1.77rem");
				g2PvChart.changeSize(351, 170).forceFit();;
			}
		});

## G2 的版本以及使用环境

- G2 版本： 1.2.0
- 使用环境： Mac OS X, Chrome 40...

如果是其他的问题，请按照如下模板来提 issue,并打上 label，真心感谢~~~

## 我的问题
g2PvChart.label 只能返回一个字符串么？能不能自定义html

## 我的期望

...

**Comment by dxq613** [comment]
https://g2.alipay.com/tutorial/label.html
