### ISSUE TITLE
坐标轴y的显示范围动态变化问题

### ISSUE THREAD

**Issue by hengdezhu** [antvis/feedback#104]
如果是 G2 的使用问题，请您按照下面的模板来提 issue，并打上 label，真心感谢~~~

## 我的需求/我的问题
在使用G2图表功能过程中发现坐标轴的y的显示范围是变化的，请问应该如何在绘制坐标轴的时候规定y轴的显示范围。谢谢您。
## 数据以及出现问题的源代码

		var data = [
			{month: '0', temperature: 7.0},
			{month: '1', temperature: 6.9},
			{month: '2', temperature: 9.5},
			{month: '3', temperature: 14.5},
			{month: '4', temperature: 18.2},
			{month: '5', temperature: 21.5},
			{month: '6', temperature: 25.2},
			{month: '7', temperature: 26.5},
			{month: '8', temperature: 27.3},
			{month: '9', temperature: 28.3},
			{month: '10', temperature: 13.9},
			{month: '11', temperature: 9.6},
			{month: '12', temperature: 7.0},
			{month: '13', temperature: 6.9},
			{month: '14', temperature: 9.5},
			{month: '15', temperature: 14.5},
			{month: '16', temperature: 18.2},
			{month: '17', temperature: 21.5},
			{month: '18', temperature: 25.2},
			{month: '19', temperature: 26.5},
			{month: '20', temperature: 27.3},
			{month: '21', temperature: 28.3},
			{month: '22', temperature: 13.9},
			{month: '23', temperature: 9.6}
		]
		var hdata = []
		var j
		var str
		for(j = 0; j < 24; j++) {
		  str = '{"month": "' + j + '", "temperature": null}'
		  str = '{"month": "' + j + '", "humidity": null}'
		  hdata[j] = JSON.parse(str)
		}
		hdata[22].humidity = 15
		hdata[23].humidity = 20
		
		function circulation () {
			var i, temp, htemp
			temp = data[0].temperature
			htemp = hdata[0].humidity
			for(i = 0; i < data.length - 1; i++) {
				data[i].temperature = data[i+1].temperature
				hdata[i].humidity = hdata[i+1].humidity
			}
			data[i].temperature = temp
			hdata[i].humidity = htemp
			chart.changeData(data)
			chart2.changeData(hdata)
		}

		var chart = new G2.Chart({
			id: 'c1',
			width: 400,
			height: 200,
			animate: false
		})
		var chart2 = new G2.Chart({
			id: 'c2',
			width: 400,
			height: 200
		})
		chart.source(data, {
			month: {
				alias: '时间',
				range: [0, 1]
			},
				temperature: {
				alias: '温度(°C)'
			}
		})
		chart2.source(data, {
			month: {
				alias: '时间',
				range: [0, 1]
			},
				humidity: {
				alias: '湿度(%)'
			}
		})
		chart.line().position('month*temperature').size(2)
		chart2.line().position('month*humidity').size(2)
		chart.guide().line([0,32],[23,32],{stroke: 'red'})
		chart.render()
		chart2.render()
		var timerChange=window.setInterval("circulation()",1000)
		function rerun () {
			timerChange=window.setInterval("circulation()",1000)
		}

## G2 的版本以及使用环境

- G2 版本： 
<script src="https://a.alipayobjects.com/g/datavis/g2/2.2.0/g2.js"></script>
- 使用环境： 微信web

**Comment by dxq613** [comment]
声明列定义 ：

temperature: {
   alias: '温度(°C)',min: 0, max: 30
}
