### ISSUE TITLE
y轴的min和max设置问题【急求】

### ISSUE THREAD

**Issue by SlimJason** [antvis/feedback#108]
如果是 G2 的使用问题，请您按照下面的模板来提 issue，并打上 label，真心感谢~~~

## 我的需求/我的问题
y轴最低要求显示0，这个min在哪里设置啊？？？？
下面这个就最高685，但是最低从200开始了，找不到哪里设置最低
## 数据以及出现问题的源代码

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>柱状图</title>
    <link rel="stylesheet" href="https://os.alipayobjects.com/s/prod/g2/static/doc-b57e62881a0344ecde9e68c4ce312143.css"/>
    
    <script src="https://a.alipayobjects.com/jquery/jquery/1.11.1/jquery.js"></script>
    <script src="https://a.alipayobjects.com/g/datavis/g2-mobile-all/2.1.7/index.js "></script>
  </head>
  <body>
    <canvas id="c1" style="width:416px;height:218px;"></canvas>
    
    <script>
      GM.Global.pixelRatio = 2;
      var data = [
        {"tem":685,"city":"tokyo"},
        {"tem":200,"city":"newYork"},
        {"tem":200,"city":"berlin"}
      ];
      var chart = new GM.Chart({
        id: 'c1'
      });
      chart.source(data, {
        tem: {
          tickCount: 5
        }
      });
      //配置刻度文字大小，供PC端显示用(移动端可以使用默认值20px)
      chart.axis('city', {
        label:{
          fontSize: 14 
        },
        grid: null
      });
      chart.axis('tem', {
        label:{
          fontSize: 14 
        }  

      });
      chart.interval().position('city*tem').color('city');
      chart.render();
    </script>
    
  </body>
</html>

**Comment by simaQ** [comment]
```js
chart.source(data, {
  tem: {
    min: 0
  }
});
```

这叫列定义操作： https://g2.alipay.com/tutorial/scale.html#度量的操作-列定义
