### ISSUE TITLE
如何设置当前id元素内部只生成一个图表？急等~~

### ISSUE THREAD

**Issue by chenghaohao** [antvis/feedback#109]
如果是 G2 的使用问题，请您按照下面的模板来提 issue，并打上 label，真心感谢~~~

## 数据以及出现问题的源代码

```js
  // ...
```

## G2 的版本以及使用环境

- G2 版本： 1.2.0
- 使用环境： Mac OS X, Chrome 40...

如果是其他的问题，请按照如下模板来提 issue,并打上 label，真心感谢~~~

## 我的问题
使用vue的自定义指令过程中，指令被called两次，然后同一id下就生成了两个相同的图表
...

## 我的期望
有没有API可以设置当前id下的元素内部只生成一个图表？？
...

**Comment by simaQ** [comment]
你是不是创建的每个 chart 对象都传入了同一个 id 值？

**Comment by chenghaohao** [comment]
对。。是的。这个有没有办法处理下？

**Comment by simaQ** [comment]
一个chart 一个 html dom 哦

**Comment by chenghaohao** [comment]
好吧。那我重新处理下
