### ISSUE TITLE
怎么配置数据显示的区间

### ISSUE THREAD

**Issue by tyrion-yu** [antvis/feedback#11]
我的source里配了一个月的数据，但我可能想一个星期一个星期的查看。

**Comment by simaQ** [comment]
你的意思是一次性载入一个月的数据，但是在展示的时候希望能一周一周得交互展示是吧？

如果这样的话，建议使用 G2.Plugin.range 插件，具体的使用详见： https://g2.alipay.com/api/plugins.html#G2.Plugin.range
