### ISSUE TITLE
拆线图Y轴的度量问题

### ISSUE THREAD

**Issue by arronf2e** [antvis/feedback#110]
**如果是** G2、G2-mobile、G6、可视化基础的使用问题，请您按照下面的模板来提 issue，并打上 label，真心感谢~~~

## 数据以及出现问题的源代码

```js
     
```

## G2 or G2-mobile or G6 的版本以及使用环境

- G2 or G2-mobile or G6 版本： 2.2.1
- 使用环境： Mac OS X, Chrome 55.0.2883.95

如果是其他的问题，请按照如下模板来提 issue,并打上 label，真心感谢~~~

## 我的问题

![http://o9xap42x4.bkt.clouddn.com/75928280-7763-443F-9B76-F696BD010D3C.png](http://o9xap42x4.bkt.clouddn.com/75928280-7763-443F-9B76-F696BD010D3C.png)

凡是大于10的部分都没有了，请问这问题怎么解决
## 我的期望

...

**Comment by simaQ** [comment]
恩，您 Y 轴的数据类型是？ 如果是字符串的话，建议转换为数字类型。或者列定义声明下为 linear 类型，https://g2.alipay.com/tutorial/scale.html

**Comment by arronf2e** [comment]
@simaQ  好的，多谢，已解决
