### ISSUE TITLE
如何默认选择图例的部分？

### ISSUE THREAD

**Issue by vxzhong** [antvis/feedback#111]
## 我的需求/我的问题

chart.line().position('day*value').color('classification').shape('smooth').size(2)
如果classification是["更多", "电影", "综艺", "游戏", "电视剧", "体育", "演唱会", "景点"]，默认是全部显示的，然后可以在图例点击取消显示一类。

如何能够默认显示一部分，譬如["电影", "综艺", "游戏"]，其余是不显示的。然后通过点击显示。

## G2 or G2-mobile or G6 的版本以及使用环境

- G2  版本： 2.2.2
- 使用环境： Mac OS X

如果是其他的问题，请按照如下模板来提 issue,并打上 label，真心感谢~~~

**Comment by simaQ** [comment]
你好，请参考这个： https://antv.alipay.com/g2/doc/tutorial/start/fqas.html#如何设置图例项的初始状态


`chart.filter()` 方法

**Comment by vxzhong** [comment]
谢谢。可以了。
