### ISSUE TITLE
筛选维度如何制定初始化值

### ISSUE THREAD

**Issue by coralandbill** [antvis/feedback#12]
如果是 G2 的使用问题，请您按照下面的模板来提 issue，并打上 label，真心感谢~~~
## 数据以及出现问题的源代码

``` js
  // ...
```
## G2 的版本以及使用环境
- G2 版本： 1.2.0
- 使用环境： Mac OS X, Chrome 40...

如果是其他的问题，请按照如下模板来提 issue,并打上 label，真心感谢~~~
## 我的问题

...
## 我的期望

...

**Comment by simaQ** [comment]
你的意思是初始化的时候展示哪部分的数据么?

https://g2.alipay.com/api/  `filter(dim, remained)`

![image](https://cloud.githubusercontent.com/assets/6628666/15501181/b2ea2f82-21de-11e6-9b36-891c1f04b482.png)

**Comment by coralandbill** [comment]
## 如何设置展示的日期

如图：打圈处显示的日期范围为2015-4-20  ~ 2015-6-25
我想默认选择2015-08-28 ~ 2015-10-09 如何设置呢？

![41e3bc33-a1bf-4255-babc-fc531ced5a1e](https://cloud.githubusercontent.com/assets/10264765/15595791/8ecb046a-23f4-11e6-8cb2-2f6b4d5e07a4.png)

## G2 的版本以及使用环境
- G2 版本： 1.2.0
- 使用环境： Mac OS X, Chrome 50.0.2

**Comment by simaQ** [comment]
@TomHuangCN

**Comment by TomHuangCN** [comment]
range({
   start: '2015-08-28',
   end: '2015-10-09,
})
@coralandbill

**Comment by TomHuangCN** [comment]
注意是你source的原始数据，不是格式化后的。@coralandbill
