### ISSUE TITLE
G6: 节点合并拆分（集群）

### ISSUE THREAD

**Issue by ghost** [antvis/feedback#120]
## 我的期望

在文档中并没有看到对节点合并拆分的介绍，还希望能够添加这个功能：
1、选中几个节点合并成一个节点；
2、选中合并节点和一个节点可以再次合并；
3、合并后的节点边的处理，重叠或是隐藏再添加；
4、双击合并节点可以拆分一次合并操作；

**Comment by TomHuangCN** [comment]
这个涉及`组`的概念，近期暂勿规划
