### ISSUE TITLE
G2目前支持模块化的导入吗？

### ISSUE THREAD

**Issue by cool-conan** [antvis/feedback#13]
## 我的问题

G2目前支持模块化的导入吗？像echart那样可以直接用require引入
## 我的期望

...

**Comment by dxq613** [comment]
内部是支持的，但是由于没有开源，源码无法放出来，所以不支持这种方式。
你可以自己尝试的封装一下

**Comment by simaQ** [comment]
Hi, @lcc19941214 目前支持了，详见 https://github.com/antvis/g2
