### ISSUE TITLE
标签云（词云）显示数据量问题

### ISSUE THREAD

**Issue by nikogu** [antvis/feedback#151]
#### 问题

词云：https://antv.alipay.com/g2/demo/18-other/cloud.html
当画布不够大的时候，并未显示所有数据，如：
![111](https://user-images.githubusercontent.com/1179603/28953556-7b5afc9c-790b-11e7-9ffc-cef92cd30356.png)
![222](https://user-images.githubusercontent.com/1179603/28953557-7ccadd7c-790b-11e7-98b3-ff90137a88e2.png)

#### 版本
- g2：2.8.3
- g-cloud: 1.0.2-beta

#### 期望

无论多大画布，显示所有数据

**Comment by macross1303** [comment]
这个基本不可行 除非让字体自适应大小。  需要开放另外的属性

**Comment by bravelincy** [comment]
@macross1303 那能不能根据值从大到小优先显示呢？现在好像是反着的。
