### ISSUE TITLE
react g2上的dark主题，配色不起作用

### ISSUE THREAD

**Issue by tianxiangbing** [antvis/feedback#16]
如果是 G2 的使用问题，请您按照下面的模板来提 issue，并打上 label，真心感谢~~~
## 我的需求/我的问题

react g2上的dark主题，配色不起作用
## 数据以及出现问题的源代码

我使用的是平滑的区域图，在使用react绘出来后，区域图的底色没有任何变化，但xy轴上的字体颜色已经变了

``` js
  // ...
```
## G2 的版本以及使用环境
- G2 版本： 1.2.0
- 使用环境： Mac OS X, Chrome 40...

如果是其他的问题，请按照如下模板来提 issue,并打上 label，真心感谢~~~
## 我的问题

...
## 我的期望

...

**Comment by simaQ** [comment]
## 解决方法

底色的话，是要你自己设置整个 dom 容器的背景颜色的，我们在 demo 中使用的 `#18242E`

## 问题解释

因为整个 canvas 是透明的，并且我们的图表的绘图区域是有一部分的 margin，所以不适合直接在主题中将绘图区域的背景设置，

![image](https://cloud.githubusercontent.com/assets/6628666/15563258/6981f544-2339-11e6-878d-d67857b3796e.png)

**Comment by tianxiangbing** [comment]
找到原因了，还是g2的问题，我传的container就会这样，传id进去就可以。尝试无数遍......太坑了吧，还不开源，找个bug都找不到

**Comment by tianxiangbing** [comment]
刚才说错了，是改了
![image](https://cloud.githubusercontent.com/assets/1968778/15563689/ceed6bf8-233d-11e6-86f0-ff0713640eb5.png)这个就会挂。

**Comment by simaQ** [comment]
￼￼
![image](https://cloud.githubusercontent.com/assets/6628666/15564462/2dd32016-2345-11e6-852f-19adfe3ae828.png)   这位兄弟，可以贴个完整的代码么？

**Comment by tianxiangbing** [comment]
已经很完整了，你去一试便知了，就是改type:cat的这个，只要不跟之前的类别的值一致，背景色就会失效，会变成浅兰色。可能我用错了吧，我以为是按这个数组的顺序来的，所以我想在这里显示个其他的值，不显示key值。结果不行。。。

**Comment by dxq613** [comment]
使用formatter格式化一下数据好了
