### ISSUE TITLE
你好，每次点击用G6绘制好的canvas时，画布都会跳一下，画布的顶端跳到屏幕视口的最上方，不知道是什么问题，

### ISSUE THREAD

**Issue by PigJack** [antvis/feedback#166]
## 我的需求/我的问题：
你好，每次点击用G6绘制好的canvas时，画布都会跳一下，画布的顶端跳到屏幕视口的最上方，就像a标签跳转一样，不知道是什么问题。
## 数据以及出现问题的源代码

```js
  // ...
```

 G6 版本： 1.2.0
- 使用环境： Chrome 40...

## 我的期望
...

**Comment by TomHuangCN** [comment]
没遇到过，写个 codepen
