### ISSUE TITLE
About页面拼写错误

### ISSUE THREAD

**Issue by wintericie** [antvis/feedback#17]
http://g2.alipay.com/about/ 致谢部分，
Special thanks to Leland Wilkinson, the anthor of 《The Grammar Of Graphics》, this book served as the foundation for G2.

anthor -> author
this -> whose

顺便问一下这种issue是不是不用提在github里，可能并不是那么重要的问题。。。

**Comment by simaQ** [comment]
谢谢指正~~~ 提吧，木有关系的

**Comment by simaQ** [comment]
已更正
