### ISSUE TITLE
地图数据的问题

### ISSUE THREAD

**Issue by Acker2015** [antvis/feedback#18]
## 我的问题

G2地图坐标系要求的数据格式是什么样子的，比如要绘制一个省份的地图，那么需要提供什么样的数据来进行path的绘制？或者说可以提供一个数据结构模版供我参考？

**Comment by simaQ** [comment]
我们所有的地图的数据都是采用标准的 [geojson](http://geojson.org/)。数据可以在这里看https://github.com/antvis/resource/tree/master/geo

**Comment by dxq613** [comment]
也就是说，G2其实支持所有符合geojson标准的地图，我们仅仅提供了 世界地图、美国地图和中国地图，其他地图，自己去查找一下吧。

**Comment by Acker2015** [comment]
@simaQ @dxq613  谢谢
