### ISSUE TITLE
[新功能] legend layout 问题

### ISSUE THREAD

**Issue by bulletnoid** [antvis/feedback#19]
## 我的需求

legend layout 问题:
1. 离散的 legend 项目名称过长
2. 离散的 legend 项目过多
会导致 legend 显示不全, 没有找到相关的配置可以解决
横向排列 legend + 自动换行应当是合适的解决方式
## 数据以及出现问题的源代码

position: left / right
legend 名称过长被截断

<img width="96" alt="screen shot 2016-05-27 at 3 39 39 pm" src="https://cloud.githubusercontent.com/assets/2130336/15601472/1b2b0798-2422-11e6-98c1-632f2b20748c.png">

position: top / bottom
legend 条目被截断

<img width="793" alt="screen shot 2016-05-27 at 4 08 42 pm" src="https://cloud.githubusercontent.com/assets/2130336/15602006/581cea38-2425-11e6-9fa5-ad1e62f5b65c.png">
## G2 的版本以及使用环境
- G2 版本： 1.2.2
- 使用环境： any

**Comment by TomHuangCN** [comment]
布局在右被截断可以，设置chart({
   plotCfg: {
      margin: [100, 100, 100, 100] //规范同css
   }
})

**Comment by TomHuangCN** [comment]
在底部被截断，现在除了将画布设大还没有其它办法 ＝。＝

**Comment by dxq613** [comment]
底部换行在下个小版本提供

**Comment by simaQ** [comment]
G2 1.2.3 版本已解决。网站后续会更新上去。

https://as.alipayobjects.com/g/datavis/g2/1.2.3/index.js

解决方案：

``` js
 chart.legend( {
   itemWrap: true // 图例需要换行, 默认为 false，不换行
 });
```
