### ISSUE TITLE
使用range插件，坐标轴没有随动

### ISSUE THREAD

**Issue by tyrion-yu** [antvis/feedback#20]
是G2 的使用问题，github怎么打 label？

标签（空格分隔）： G2
## 数据以及出现问题的源代码

``` js
    var range = new G2.Plugin.range({
        id: "range",
        width: 1000,
        height: 26,
        dim: 'date'
    });

    range.source(chartSourcePC);
    range.link([chartPV1,chartPV2,chartDelay1,chartDelay2]);
    range.render();
```
## G2 的版本以及使用环境

g2 v1.2.2
range v0.0.6

用的同一个浏览器，栗子里是随动的。
## 我是图

![image](https://cloud.githubusercontent.com/assets/12961132/15604147/36bf0b8a-2431-11e6-9a04-cf9804ac56ae.png)

**Comment by TomHuangCN** [comment]
首先你得确保这四个chart，用的都是同一份数据源。

**Comment by TomHuangCN** [comment]
另外时间最好用时间戳，字符串格式化用，列定义里的mask。见度量章节https://g2.alipay.com/api/scale.html  时间 度量

**Comment by tyrion-yu** [comment]
``` javascript
'date': {
            alias: '日期',
            type: 'cat',
            values: dateMap
}
```

我的date 的type是 cat，数值是从0开始的整数，这个有影响嘛

**Comment by TomHuangCN** [comment]
可以，但如果数据源的时间数据传的是字符串，range则无法排序，需要你自己在外面将数据按日期排好序

**Comment by tianlin-yu** [comment]
谢谢，最后决定用日期格式，跟栗子一模一样，就成功了

**Comment by dxq613** [comment]
已经解决问题，关闭
