### ISSUE TITLE
教程/g2语法/绘制绘制散点图点击legend绘制统计线会有bug

### ISSUE THREAD

**Issue by Acker2015** [antvis/feedback#21]
## G2 的版本以及使用环境
- G2 版本： 1.2.0
- 使用环境： Mac OS X, Chrome 40...
## 我的问题

教程/g2语法/绘制绘制散点图点击legend绘制统计线会有bug
<img width="1016" alt="2016-05-28 10 52 57" src="https://cloud.githubusercontent.com/assets/13566616/15624785/5369be22-24c4-11e6-9ebf-a159b4af8d24.png">

**Comment by simaQ** [comment]
这是因为绘制代码中写死了数值，

``` js
chart.guide().tag([hAvg, 40], [hAvg, 120], '身高平均值: ' + hAvg.toFixed(2), {line:lineCfg});
chart.guide().tag([140, wAvg], [200, wAvg], '体重平均值: ' + wAvg.toFixed(2), {line:lineCfg});
chart.render();
```

**Comment by dxq613** [comment]
辅助线由于是使用了固定数值来绘制的辅助线，下个小版本，提供几个特殊的关键字：
- max ：当前坐标轴（度量）的最大值
- min： 当前坐标轴（度量）的最小值

``` js
chart.guide().tag([hAvg,'min'], [hAvg,'max'], '身高平均值: ' + hAvg.toFixed(2), {line:lineCfg});
chart.guide().tag(['min', wAvg], ['max', wAvg], '体重平均值: ' + wAvg.toFixed(2), {line:lineCfg});
chart.render();

```

**Comment by simaQ** [comment]
G2 1.2.3 版本已解决。

https://as.alipayobjects.com/g/datavis/g2/1.2.3/index.js

解决方案如 @dxq613 所述。
