### ISSUE TITLE
G2 range插件怎么设置初始化时显示100%的数据，另外在非100%时辅助线不能显示

### ISSUE THREAD

**Issue by tianlin-yu** [antvis/feedback#22]
label :g2
## G2 range插件怎么设置初始化时显示100%的数据，另外在非100%时辅助线不能显示

![image](https://cloud.githubusercontent.com/assets/14886858/15625611/00bb2f82-24e0-11e6-8e40-63b14b265796.png)

![image](https://cloud.githubusercontent.com/assets/14886858/15625613/0de5511a-24e0-11e6-89b9-fd53d6250388.png)

辅助线挂了

**Comment by TomHuangCN** [comment]
```
range({
  start: dimValue, // 横坐标维度原始数据起始
  end: dimValue // 横坐标维度原始数据结束
});
```

**Comment by dxq613** [comment]
辅助线的问题跟 #21 的问题是同一个问题，在小版本中解决

**Comment by simaQ** [comment]
G2 1.2.3 版本已解决。

https://as.alipayobjects.com/g/datavis/g2/1.2.3/index.js
