### ISSUE TITLE
地图类图表不能在本地运行

### ISSUE THREAD

**Issue by cbbing** [antvis/feedback#23]
## 数据以及出现问题的源代码

getJSON取得的url是在阿里服务器上，在本地是无法获取到这个文件：/data.json?filename=china',

``` js
  <script>
      $.getJSON('/data.json?filename=china', function(mapData) {
        var Stat = G2.Stat;
```
## G2 的版本以及使用环境
- G2 版本： 1.2.0
- 使用环境： Mac OS X, Chrome 40
## 我的期望

/data.json?filename=china',数据支持外链，能够在本地运行。

**Comment by simaQ** [comment]
我们将地图数据都放在了 https://github.com/antvis/resource 库中，地图数据 在 geo 目录里面。https://github.com/antvis/resource/blob/master/geo/china.json

**Comment by Acker2015** [comment]
1.可以自己搭一个简单的提供静态文件的服务器，将[china.json](https://github.com/antvis/resource/blob/master/geo/china.json)中的文件放在服务器上请求到本地绘制地图
2.另外一个简单一点并且快一点可以绘制出地图的办法就是将上述链接中的文件存到一个js文件中作为变量，然后在绘制地图的文件中引入就可以了

**Comment by cbbing** [comment]
@Acker2015  github可以作为一个静态服务器。
上述json文件我从下面的链接取到了。 https://raw.githubusercontent.com/antvis/resource/master/geo/china.json
