### ISSUE TITLE
G2是基于D3.js开发的吗？

### ISSUE THREAD

**Issue by gaojing007** [antvis/feedback#24]
如题，G2是基于D3.js开发的吗。对比D3.js,G2的特点是？

**Comment by dxq613** [comment]
G2 不是基于D3.js开发的，对比D3：
- 语法更简单、易用
- 数据和图形属性的映射自动完成
- 一些复杂图表根据数据功能使用语法解析，更容易理解

欠缺的地方：
- 自定义图形能力还没发布
- 交互功能开放比较少
- 网络、树状图当前版本没有支持

后面的版本中会对图形能力、数据的异构问题、交互能力都会进行扩展。我们会持续开放，使G2成为一个更加易用，功能强大的可视化工具
