### ISSUE TITLE
[bug] axis label 旋转问题

### ISSUE THREAD

**Issue by bulletnoid** [antvis/feedback#25]
## 我的需求/我的问题

label 旋转后没有对齐到顶端, 对于超长的 label 非常明显, 且 label 会超过坐标轴
## 数据以及出现问题的源代码

``` js
chart.axis('someDim', {
  labels: {
    label: {
      'text-anchor': 'start' // 试验发现此项对旋转的 label 不起作用
    },
    autoRotate: true
  }
}
```

<img width="386" alt="screen shot 2016-06-01 at 2 31 43 pm" src="https://cloud.githubusercontent.com/assets/2130336/15700594/57d97e70-2807-11e6-8668-e7b4b91ab98d.png">
## G2 的版本以及使用环境
- G2 版本： 1.2.2
- 使用环境： any

**Comment by dxq613** [comment]
自动计算完成后，文本对齐方式的设置存在问题，下面版本修复这个问题。坐标轴文本的对齐方式，全部都是自动计算的，如果能够全部计算正确，用户手工设置起始意义不大。

**Comment by simaQ** [comment]
G2 1.2.3 版本已解决。

https://as.alipayobjects.com/g/datavis/g2/1.2.3/index.js

**Comment by nnnnnice** [comment]
目前设置autoRotate的情况下文本对齐方式不会出错，若是自己设置rotate依然会导致这样的问题
