### ISSUE TITLE
[Bug]文档错误

### ISSUE THREAD

**Issue by HeavenDuke** [antvis/feedback#26]
## 我的问题

[Data 数据：https://g2.alipay.com/tutorial/data.html](https://g2.alipay.com/tutorial/data.html)
在这一页中Frame静态方法的说明部分：  
- sum(frame,x) Number 计算列x的和
- max(frame,x) Number 计算列x的最大值
- min(frame,x) Number 计算列x的最小值
- **sum(frame,x) Number 计算列x的最大值**

这里的第二个sum应该是写错了~
...

**Comment by dxq613** [comment]
是的，写错了，改过来

**Comment by simaQ** [comment]
已改。
