### ISSUE TITLE
[Bug]无法改变坐标轴刻度字体的大小

### ISSUE THREAD

**Issue by GuoMark** [antvis/feedback#27]
## 我的需求/我的问题

无法改变坐标轴刻度字体的大小
## 数据以及出现问题的源代码

比如用如下的例子（在实际的使用中，‘dim’会对应为真实数据源中的字段名），坐标轴刻度文本没有任何变化，实际显示总是为缺省的‘12’。
chart.axis('dim', {
  labels: {
    label: {
      'font-size': '18'// 文本大小
    }
  }
})
## G2 的版本以及使用环境
- G2 版本： 1.2.2
- 使用环境： Chrome Version 50.0.2661.102 m

**Comment by TomHuangCN** [comment]
下个版本修复

**Comment by GuoMark** [comment]
有什么hardcode的方法，可以在新版本出来前绕过这个问题吗？

**Comment by dxq613** [comment]
试试：

``` js
label: {
'font': '18px  arial'// 文本大小
}

```

**Comment by GuoMark** [comment]
还是不行。这个特性对我来说挺重要的，如果能找到一个临时设置成功的方法，那就太有帮助了！

**Comment by TomHuangCN** [comment]
```
        chart.axis('dim',{
          labels: {
            label:{
              fontFamily: 'sans-serif',
              'font-size': 20
            }
          }
        });
```

定义一下字体

**Comment by GuoMark** [comment]
It did work. Many thanks!
