### ISSUE TITLE
[Bug]区域图不支持连续的null值

### ISSUE THREAD

**Issue by GuoMark** [antvis/feedback#28]
## 我的需求/我的问题

区域图只支持间断的null值，不支持连续的null值，比如连续2个null。控制台会报如下错误：
Uncaught TypeError: Cannot read property 'x' of undefined
## 数据以及出现问题的源代码

出错的代码是根据使用示例https://g2.alipay.com/demo/03-area/area-null.html
稍加修改数据而成。

```
  var data= [
    {"year": "1986", "ACME": 162, "Compitor": 42},
    {"year": "1987", "ACME": 134, "Compitor": 54},
    {"year": "1988", "ACME": 116, "Compitor": 26},
    {"year": "1989", "ACME": 122, "Compitor": 32},
    {"year": "1990", "ACME": 178, "Compitor": 68},
    {"year": "1991", "ACME": 144, "Compitor": 54},
    {"year": "1992", "ACME": 125, "Compitor": 35},
    {"year": "1993", "ACME": 176, "Compitor": 66},
    {"year": "1994", "ACME": 156},
    {"year": "1995", "ACME": 195},
    {"year": "1996", "ACME": 215, "Compitor": 115},
    {"year": "1997", "ACME": 176, "Compitor": 36},
    {"year": "1998", "ACME": 167, "Compitor": 47},
    {"year": "1999", "ACME": 142, "Compitor": 72},
    {"year": "2000", "ACME": 117, "Compitor": 37},
    {"year": "2001", "ACME": 113, "Compitor": 23},
    {"year": "2002", "ACME": 132},
    {"year": "2003", "ACME": 146, "Compitor": 46},
    {"year": "2004", "ACME": 169, "Compitor": 59},
    {"year": "2005", "ACME": 184, "Compitor": 44}
  ];
```
## G2 的版本以及使用环境
- G2 版本： 1.2.2
- 使用环境：Chrome Version 50.0.2661.102 m

**Comment by simaQ** [comment]
恩，确实是，我跟进下

**Comment by dxq613** [comment]
1.2.4 版本已经修复

**Comment by dxq613** [comment]
https://as.alipayobjects.com/g/datavis/g2/1.2.4/index.js

**Comment by GuoMark** [comment]
这个问题解决的不够彻底，还是把示例https://g2.alipay.com/demo/03-area/area-null.html
稍加修改数据作为测试实例。如果列表最后出现连续2个null，也会报错。

  var data= [
    {"year": "1986", "ACME": 162, "Compitor": 42},
    {"year": "1987", "ACME": 134, "Compitor": 54},
    {"year": "1988", "ACME": 116, "Compitor": 26},
    {"year": "1989", "ACME": 122, "Compitor": 32},
    {"year": "1990", "ACME": 178, "Compitor": 68},
    {"year": "1991", "ACME": 144, "Compitor": 54},
    {"year": "1992", "ACME": 125, "Compitor": 35},
    {"year": "1993", "ACME": 176, "Compitor": 66},
    {"year": "1994", "ACME": 156},
    {"year": "1995", "ACME": 195},
    {"year": "1996", "ACME": 215, "Compitor": 115},
    {"year": "1997", "ACME": 176, "Compitor": 36},
    {"year": "1998", "ACME": 167, "Compitor": 47},
    {"year": "1999", "ACME": 142, "Compitor": 72},
    {"year": "2000", "ACME": 117, "Compitor": 37},
    {"year": "2001", "ACME": 113, "Compitor": 23},
    {"year": "2002", "ACME": 132},
    {"year": "2003", "ACME": 146, "Compitor": 46},
    {"year": "2004", "ACME": 169},
    {"year": "2005", "ACME": 184}
  ];

G2 版本： 1.2.5
使用环境：Chrome Version 50.0.2661.102 m
