### ISSUE TITLE
[Bug?]图例位置问题

### ISSUE THREAD

**Issue by HeavenDuke** [antvis/feedback#29]
## 我的问题

在尝试设置多个字段Legend的位置时发现：**通过`chart.legend(dim, cfg)`针对不同字段设置不同的position是无效的。**

下面是我用的例子，数据集就是样例数据集中的car.json。

``` javascript
var Frame = G2.Frame;
var frame = new Frame(data);
var chart = new G2.Chart({
    id : 'c1',
    width : 800,
    height : 400
});
chart.source(frame);
chart.tooltip(true, {
    title: null
});
chart.point().position("depth*table").color('cut').shape("clarity");
chart.legend("cut", {
    position: "top"
});
chart.legend("clarity", {
    position: "right"
});
chart.filter("cut", ["Ideal", "Good"]);
chart.render();
```

但是画出来之后可以看到所有的图例都被放到了右侧（运行效果在这里：[http://heavenduke.github.io/learningg2/legend_demo/demo.html](http://heavenduke.github.io/learningg2/legend_demo/demo.html)）。而如果注释掉第二个legend的设置，整个图例又都移到了上面。请问G2现在还不支持在不同位置绘制不同字段的图例吗？
...

**Comment by simaQ** [comment]
恩，是的呢，目前还不支持绘制不同位置的图例。上周我也在考虑这个问题，这个功能是否必需

**Comment by dxq613** [comment]
1.2.4 已经修复：https://as.alipayobjects.com/g/datavis/g2/1.2.4/index.js
