### ISSUE TITLE
关于扰动点图的一点疑问

### ISSUE THREAD

**Issue by Huang77** [antvis/feedback#3]
## 我的问题

看 https://g2.alipay.com/demo/01-point/custom-color.html 上的示例扰动点图有点不是很明白，请问这个图中每个点的横坐标是编码的是什么呢？

横坐标现在是类别型的，但是数据点在类别的区域内也有不同的横坐标。如果没有编码什么维度，只是随机分布的话，会不会有点引起用户的误解呢？ （比如我> <）

**Comment by dxq613** [comment]
扰动点图，其实只有在分类的范围内进行扰动，因为每个分类在横坐标上都有一个范围，那么只要点落到这个范围内用户就不会误解，如果不进行扰动，很多同一个分类的数据就会层叠起来。
连续数据是不能进行扰动的，如果扰动就会导致数据的值变化
