### ISSUE TITLE
[Bug]教程中关于Stat的内容问题

### ISSUE THREAD

**Issue by HeavenDuke** [antvis/feedback#30]
## 我的问题

教程中在[Stat#density](https://g2.alipay.com/tutorial/stat.html#density)的后面提到了kernelType，但是在API中却没有体现这个内容。并且API中出现了这种写法：**density.kernel.('x*y')**
可以看到在括号前面出现了令人迷惑的点号，希望能够把这里写得清楚一些。在[Stat#smooth](https://g2.alipay.com/tutorial/stat.html#smooth)中也出现了类似的内容。

此外，在调试的过程中我发现[Stat#density]这里可以传进去第二个参数，这个参数的作用是什么？现在Stat的API文档里面并没有说明相关的API，只是给出了向教程的链接，希望API文档能够把这些细节上的内容写清楚一些。
...

**Comment by simaQ** [comment]
> 可以看到在括号前面出现了令人迷惑的点号

尴尬，这个是我的笔误... 我尽快更新下网站；

> 此外，在调试的过程中我发现[Stat#density]这里可以传进去第二个参数，这个参数的作用是什么？

第二个参数 bandWidth 代表核函数带宽占数据总范围的百分比，是可选的，默认0.01。

恩，统计这块我会继续完善更新的，感谢反馈~

**Comment by simaQ** [comment]
Stat 已经更新了部分~ https://g2.alipay.com/tutorial/stat.html
