### ISSUE TITLE
[Bug]Legend和坐标轴mark重叠

### ISSUE THREAD

**Issue by HeavenDuke** [antvis/feedback#31]
## 我的问题

在绘制图表的时候我发现直角坐标系的坐标轴上的mark标记会在一些情况下和图例重叠在一起：
1. 不翻转，和左侧还有下侧的图例重叠
2. 翻转x轴，和右侧的图例重叠
3. 翻转y轴，和上侧的图例重叠

其中一个例子在这里：http://heavenduke.github.io/learningg2/coordinate_operation/issue1/demo.html

我知道这个在绝大多数情况可以通过调整图例位置来避开，但是还是希望能提升一下这部分的适配能力。
...

**Comment by dxq613** [comment]
legend的位置是通过图表绘图区域进行对齐的，上下左右，没有考虑跟坐标轴的文本的对齐问题，所以才给legend提供了 dx,dy的参数来设置偏移量。

![绘制区域](https://zos.alipayobjects.com/rmsportal/PswABqxEFcVTkiU.png)

这种自适应避开文本折叠的问题其实很难解决，文本的长度不定，旋转方向不定。以前我们的策略是legend跟整个画布的右端进行对齐，但是这种方式跟绘图区域重叠的可能性更大。所以综合考虑还是让用户自己调整dx,dy来设置偏移量。
