### ISSUE TITLE
[Bug]坐标系的reflect

### ISSUE THREAD

**Issue by HeavenDuke** [antvis/feedback#32]
## 我的问题

这部分有两部分问题，一部分是官方文档中说reflect的翻转是x或者y方向，但是文档示例中给出了`chart.coord().rotate(70).scale(1.5, 1.5).reflect('xy').transpose();`这样的示例。目前测试的结果是上面这种写法不会同时反转坐标轴，只有`.reflect('x').reflect('y')`才可以，我想这个地方能不能写得更明白一些。

另一部分是运行时的问题：
1. 翻转时坐标轴mark和图例重叠的问题（已经在[https://github.com/antvis/feedback/issues/31](https://github.com/antvis/feedback/issues/31)中做了具体陈述）
2. 对y轴翻转时，坐标轴上的mark会超出屏幕外。示例：[http://heavenduke.github.io/learningg2/coordinate_operation/issue2/demo.html](http://heavenduke.github.io/learningg2/coordinate_operation/issue2/demo.html)
3. 在同时进行transpose与任何一轴的翻转时，坐标轴上的mark会被绘制到坐标系里面，和geom重叠在一起。示例：[http://heavenduke.github.io/learningg2/coordinate_operation/issue3/demo.html](http://heavenduke.github.io/learningg2/coordinate_operation/issue3/demo.html)和[http://heavenduke.github.io/learningg2/coordinate_operation/issue4/demo.html](http://heavenduke.github.io/learningg2/coordinate_operation/issue4/demo.html)
...

**Comment by dxq613** [comment]
1. #31 中进行了回复
2. 你这个demo上不是marker绘制到坐标系外面了，而是坐标轴上的文本在外面了，这个原因在于图表的margin不是自动计算的而是默认配置，用户可以更改的
   
   ``` js
     var chart = new Chart({margin: [top,right,bottom,left]});
   ```
   
   之所以没有自动计算margin也有很多考虑，所以这时候只要调整一下margin即可。
3. transpose后的坐标轴文本对齐确实存在问题，现在文本的对齐，位置是通过向量计算出来的，通用性不够，后面版本里面重构这部分对齐逻辑。
