### ISSUE TITLE
数据比较大时的性能问题

### ISSUE THREAD

**Issue by travilyu** [antvis/feedback#33]
## 我的问题

数据量比较大时渲染速度很慢
## 我的期望

几万以上数据时，二维数组的concat以及values函数计算非常慢。可以改成直接嵌套push，以及用Set直接在values函数中去重。实测改了之后好了很多很多。。

**Comment by dxq613** [comment]
你指的是哪里的函数？DataFrame的函数么，二维数组的concat倒是可以改成 Array.prototype.push.apply(arr, sub)，但是values 去重的话，用对象的set去处理，出来的values的顺序是按照字母顺序排序的，大部分情况，特别是字符串字段，还是需要按照默认顺序来取values的

**Comment by travilyu** [comment]
源码里看不出来是哪的。。就是profile到了，看起来就是你说的地方。。
去重直接用了es6的Set。。算作弊吧。。不过可以用hash去重，数组记顺序，就是通用hash不太好找 @-@

**Comment by dxq613** [comment]
创建一个空的对象去重即可，不过顺序如果还用数组来存储的话，性能确实能好不少。

```
var obj = {};
var rst = []
if (!obj[key]) {
  obj[key] = true;
  rst.push(key);
} 
```

**Comment by dxq613** [comment]
@simaQ 看看这样实现是否比原先更好。

**Comment by simaQ** [comment]
好的，我跟进下这个问题
