### ISSUE TITLE
主题dark并没有把背景设置成暗色调

### ISSUE THREAD

**Issue by craig0** [antvis/feedback#35]
如果是 G2 的使用问题，请您按照下面的模板来提 issue，并打上 label，真心感谢~~~
## 数据以及出现问题的源代码

var Global = G2.Global; // 获取 Global 全局对象
var Theme = G2.Theme; // 获取 Theme 对象，包含三个属性： 'default' 'dark' 'cheery' 对应主题名 
Global.setTheme(Theme['dark']);
## G2 的版本以及使用环境
- G2 版本： 1.2.3
- 使用环境： Chrome 40...

**Comment by dxq613** [comment]
这个背景颜色没有在canvas上绘制，可以直接加到chart的容器上， 

``` html
<div class="background:#18242E;"></div>
```

也可以设置chart的属性：

``` js
new chart({
  plotCfg: {
    border: {fill: '#18242E'}
  }
});

```

这个属性确实应该在dark的皮肤中设置的，下个小版本修复

**Comment by craig0** [comment]
原来是这样 谢谢啦^ ^
