### ISSUE TITLE
legend不显示def里面的alias的名称

### ISSUE THREAD

**Issue by iwege** [antvis/feedback#36]
## 我的问题

legend 无法吃进def里面alias属性，必须要求数据的key是中文
## 我的期望

legend能显示def里面的alias属性，期望的行为与坐标轴一样

**Comment by TomHuangCN** [comment]
应该是一致的，确认一下字段名是否匹配

**Comment by iwege** [comment]
如果是简单的没问题，但是如果复杂一点涉及到计算的，就有问题。
这个时候只能要求key是中文才能做到tooltip也是中文的。代码如下：

https://jsfiddle.net/iwege/xp0xzgfu/

**Comment by TomHuangCN** [comment]
```
        type:{
          alias:'测试 type',
          formatter: function(value) {
            return value === 'satisfied' ? "满意": "不满意";
          }
        }
```

合并frame后，已经不是字段名，而是type的value了，要这样写

**Comment by iwege** [comment]
... 我找遍了整个文档就只有chart对象那一个页面有一个formatter 非常简略的描述
建议增加一下formatter和alias的区别还有用法....

**Comment by iwege** [comment]
另外如果说转化为value，那么是不是说type这个地方就变成 ‘cat’ 类型？还是说这个并不属于标准类型？

**Comment by dxq613** [comment]
这部分文档移动到 api里面了，https://g2.alipay.com/api/scale.html

``` js
Frame.combinColumns(frame, ['satisfied', 'dissatisfied'], 'count', 'type', 'genre'); // 将'satisfied','dissatisfied'合并成'count'列各自的类型 type = 'satisfied' 或者 type = 'dissatisfied'
```

这个地方没有那么复杂，其实是就是将2列合并成了一列,一条数据变成了2条数据

``` js
{genre: 'Sports', sold: 27500, satisfied: 25000, dissatisfied: 2000},
```

转变成了

``` js
{genre: 'Sports', type: 'satisfied', count: 25000},
{genre: 'Sports', type: 'dissatisfied', count: 2000},
```

按照正常的数据映射写语法好了，这些仅仅是数据的预处理，如果你后台的数据本身就符合这个形式，完全不需要处理。

你这里的问题是把type的内容给格式化，而不是type本身的alias

**Comment by iwege** [comment]
<del>@dxq613 这个理解上没太多问题，关键是你转化了之后的格式，理论上是否是变成了cat，那是否能配置 </del>

``` js
{
  type:{
   type: 'cat',
   values: ['满意','不满意']  
}
}
```

<del>这样来解决呢？ </del>

以上方法不能解决问题... 只能用formatter的方式来解决。

**Comment by dxq613** [comment]
在type:'cat'的列定义里面定义values的用途有下面2种：
- 当前分类类型的值是枚举类型 0,1,2这种情况，会根据Index跟values的值对应
- 指定当前分类的顺序，不过此时必须values的值跟 数据中的值对应

如果数据里面的值跟values里面的值不对应，此时没法确保最终输出是什么，G2的逻辑是先取一下对应列的值，去重，如果此时取出来的值跟values恰巧一一对应，那恭喜你。。。

**Comment by iwege** [comment]
@dxq613 `formatter`的作用还是比较大的，但是API介绍上面就一句话过了，建议多给一点代码描述。
