### ISSUE TITLE
一点小问题，不足关注

### ISSUE THREAD

**Issue by zzf88521** [antvis/feedback#39]
不是代码问题，G2官网介绍G2特性的时候，有一个错别字  “一套强大的与法”，应该是“一套强大的语法”。
我并不吹毛求疵，而是不小心看到了，所以提醒一下，如有冒犯，敬请谅解。

邮箱 : 447833339@qq.com

**Comment by simaQ** [comment]
哈哈，谢谢~~~ 为你的细心点赞
