### ISSUE TITLE
有G2 react的使用教程吗？

### ISSUE THREAD

**Issue by accaolei** [antvis/feedback#4]
有G2配合react的使用教程，或者和Ant Design of React的结合使用

**Comment by kaiailu** [comment]
有个react库，很快就会开放给大家使用，敬请期待。

**Comment by kaiailu** [comment]
G2本身就是javascript做的，能适应任何javascript环境，react也是javascript环境所以能用，官方不会出react下的G2使用方法教程

**Comment by jaredleechn** [comment]
@accaolei 

💥 g2-react bump, see:
- homepage: https://github.com/antvis/g2-react
- doc: https://antvis.github.io/g2-react/

**Comment by accaolei** [comment]
thinks  @jaredleechn
