### ISSUE TITLE
折线图

### ISSUE THREAD

**Issue by yangxiaopei** [antvis/feedback#41]
如果是 G2 的使用问题，请您按照下面的模板来提 issue，并打上 label，真心感谢~~~
## 我的需求/我的问题

请问下折线图可以在图上直接显示每个点的数值吗
## 数据以及出现问题的源代码

``` js
  // ...
```
## G2 的版本以及使用环境
- G2 版本： 1.2.0
- 使用环境： Mac OS X, Chrome 40...

如果是其他的问题，请按照如下模板来提 issue,并打上 label，真心感谢~~~
## 我的问题

...
## 我的期望

...

**Comment by simaQ** [comment]
可以的，参照 http://g2.alipay.com/demo/02-line/path.html， 使用 `label('dim')`

如： 

```
 chart.path().position('price*consumption').label('year', function(val) {
        return val + '年';
      }).size(2);
```

具体用法： http://g2.alipay.com/api/geom.html#label
