### ISSUE TITLE
关于"二维扰动点图"的数据源问题

### ISSUE THREAD

**Issue by yuyang2015** [antvis/feedback#42]
请问能否提供下二维扰动点图，示例源码里"/data.json?filename=diamond"这个数据的文件呢？或者数据片断也可以。万分感谢:-)

**Comment by simaQ** [comment]
恩恩，数据源在这个 repo 里面哦： https://github.com/antvis/resource/tree/master/data， 扰动点图的数据： https://github.com/antvis/resource/blob/master/data/diamond.json

**Comment by yuyang2015** [comment]
好贴心。qqq
