### ISSUE TITLE
移动端使用

### ISSUE THREAD

**Issue by lmooc** [antvis/feedback#43]
如果是 G2 的使用问题，请您按照下面的模板来提 issue，并打上 label，真心感谢~~~
## 我的问题

移动端怎么使用，添加<meta name="viewport" content="width=device-width, initial-scale=1" user-scalable="no">好像没有等比缩放
## 我的期望

移动端可以等比缩放

**Comment by dxq613** [comment]
移动端的G2有单独存在的版本，g2-mobile，但是现在还在内测阶段，没正式放出来。

**Comment by dxq613** [comment]
当前的g2可以宽度自适应了，forceFit:true，但是移动端的方案不一样吧。

**Comment by lmooc** [comment]
希望越来越好。。
