### ISSUE TITLE
官网页面错位

### ISSUE THREAD

**Issue by geekplux** [antvis/feedback#44]
## 我的问题

官网教程页面错位，如图：

<img width="929" alt="screen shot 2016-06-28 at 13 58 00" src="https://cloud.githubusercontent.com/assets/3816105/16405247/a8d8bf20-3d38-11e6-8d1d-57c142a1c76b.png">

下拉之后，左右两边的 nav 的 position 都变成了 fixed ，中间的 `.doc-content` 也应该做一下处理

**Comment by simaQ** [comment]
多谢多谢！
