### ISSUE TITLE
请问有没有绘制根据后台传过来的数据实时更新图表的代码示例？

### ISSUE THREAD

**Issue by stand1921** [antvis/feedback#45]
## 我的需求/我的问题

1.请问有没有绘制实时动态变化的代码例子，我目前在使用股票图做一个实时显示股票数据的应用，图中的数据应根据后台传过来的数据动态更新。目前我按照官网中的例子，每接受一次数据就chart.source(data);chart.render()一下，图中数据是叠加显示，而不是根据数据变化而变化。

2.坐标轴和示例等部分能不能和数据的线条分开绘制，比如有时候数据未到达，还是想先把坐标轴画出来给用户看，等数据传输到之后再画数据的线条。

3.请问G2.Plugin.range有没有设定范围值的参数，目前我绘制的实时股票图，每次接受数据时就range.render()一次，渲染后每次range条的范围都回到默认值，希望能保持用户所划分的范围。
## G2 的版本以及使用环境
- G2 版本： 1.2.0
- 使用环境： win10, Chrome 49...

**Comment by dxq613** [comment]
1. 数据改变有个专门的接口：chart.changeData(data)，所有的信息就可以刷新。
2. 如果你想实现你说的效果，需要定义一下你图形语法里面的数据字段，让g2知道你的数据字段的信息，设置空数组即可，当数据到达时，changeData即可

``` js
var data = []; // 初始空数组
var defs = {
 a: {
   type:'cat',
   values: ['a', 'b','c']
 },
 b: {
  type: 'time',
  min: '2012-01-01',
  max: '2014-05-01'
 },
 c: {...}
};

chart.source(data,defs);

chart.line().position('b*a').color('c');

chart.render();
```
1. plugin.range 的问题 @TomHuangCN

**Comment by TomHuangCN** [comment]
### 方案一：销毁重新生成

```
new Range({
  start: dimValue, // 横坐标维度 原始 数据起始
  end: dimValue // 横坐标维度 原始 数据结束
});
```

**Comment by TomHuangCN** [comment]
### 方案二：设置range参数重绘

```
range.set('range', [10, 90]) // 数组里传0～100的数值表示范围
range.render();
```

**Comment by stand1921** [comment]
谢谢
