### ISSUE TITLE
根据不同的names绘制不同的图形

### ISSUE THREAD

**Issue by decsev** [antvis/feedback#46]
如果是 G2 的使用问题，请您按照下面的模板来提 issue，并打上 label，真心感谢~~~
## 数据以及出现问题的源代码

下面是数据：
data = [{datetime: "2016-06",dateval: 10000,names: "name1"},{datetime: "2016-06",dateval: 10012,names: "name1"},{datetime: "2016-06",dateval: 10552,names: "name2"},{datetime: "2016-06",dateval: 100812,names: "name2"}]

``` js
  // ...
```
## G2 的版本以及使用环境
- G2 版本： 1.2.0
- 使用环境： win7

如果是其他的问题，请按照如下模板来提 issue,并打上 label，真心感谢~~~
## 我的问题

能否根据不同的names绘制不同的图形，如name1时画line,name2时画area，且它们存在同一个座标内
...
## 我的期望

...

**Comment by dxq613** [comment]
折线图和区域图其实2种图表，每种图表又有不同的shape
https://g2.alipay.com/api/geom.html#shapedimshapes
- 折线图： 'line','smooth','dot','dash','dotSmooth','spline'
- 区域图：'area','smooth','line','dotLine','smoothLine','dotSmoothLine'

你可以使用area，然后指定不同的shape

``` js
chart.area().position('datetime* dateval').shape('names', function(names){
  if(names == 'name1') {return 'line';} else return 'area';
});
```
