### ISSUE TITLE
添加3D chart

### ISSUE THREAD

**Issue by yunzhizhou** [antvis/feedback#47]
## 我的期望

什么时候可以添加3D chart呀

**Comment by dxq613** [comment]
你是想要伪3D效果，还是，需要有x,y,z3个坐标轴的图，这是2类图

**Comment by dxq613** [comment]
目前在开发的版本是2.0，3D图表计划在3.0开发，伪3D效果，不考虑开发

**Comment by yunzhizhou** [comment]
期待中，3d图表更喜欢
