### ISSUE TITLE
画饼图的问题

### ISSUE THREAD

**Issue by HuMonkey** [antvis/feedback#48]
## G2 的版本以及使用环境
- G2 版本： 1.2.0
- 使用环境： Windows 7, Chrome 40...
## 我的问题

一、画饼图的时候，图表指定图元属性用了这样一句：
**chart.intervalStack().position(Stat.summary.percent('y')).color('x');**
这里使用的数据是两个维度的，维度名分别为'x'和'y'。
结果画出来的扇形不在一个同心圆上...后来把维度名'x'改成其他（比如'type'）就好了。

二、画饼图的时候好像并没有特定的API指定饼图要根据那个维度去划分。
**chart.intervalStack().position(Stat.summary.percent('y')).color('x');**像这句代码如果把.color('x')去掉，画出的就只有一个扇形。是否可以理解为.color()执行了饼图划分的操作？

谢谢~

**Comment by HuMonkey** [comment]
是否因为x和y都是特殊关键字，所以数据的字段名不能用？

**Comment by dxq613** [comment]
1. 因为position有2个映射方向，x,y,所以内部代码中会生成x,y字段，如果你的语法中,x,y跟position的x,y一致起来不会出错，但是一旦x,y互换，就会出现问题。所以当前版本我们制定了保留字：

x,y,z,color,shape,size字段，最好不要在代码中出现，即使出现也要跟语法中的含义一致，后面的版本会修复这个问题。
1. color,shape等属性，中的分类字段会导致数据分组

感兴趣的话，读一下这篇文档： https://g2.alipay.com/tutorial/attr.html
我也正在写G2的框架设计文档：https://github.com/antvis/g2/wiki
