### ISSUE TITLE
需求 G2 生成的坐标系 是否支持 三维坐标系

### ISSUE THREAD

**Issue by alextiffy** [antvis/feedback#5]
我想请教玉伯 G2 生成的坐标系 有木有三维坐标系 ？

**Comment by kaiailu** [comment]
玉伯比较忙，我来代答。
三维坐标系，在开发中，预计一段时间后会与大家见面。敬请期待

**Comment by dxq613** [comment]
目前看来web上的展示，三维的坐标系对一般的业务帮助不大，当然从未来VR，AR的发展来看，肯定是需要的，只是展示形式没法确定。
