### ISSUE TITLE
如何在React组件中render G2 new出来的Object呢？

### ISSUE THREAD

**Issue by zhuqiuyang** [antvis/feedback#50]
如果是 G2 的使用问题，请您按照下面的模板来提 issue，并打上 label，真心感谢~~~
## 数据以及出现问题的源代码

``` js
 var chart = new G2.Chart({
      ...
      });
      chart.tooltip({
        crosshairs: true
      });
      chart.area().position('day*share');
      chart.line().position('day*share').size(3);
      chart.render();
```
## G2 的版本以及使用环境
- G2 版本： 1.2.0
- 使用环境： Mac OS X, Chrome 40...

如果是其他的问题，请按照如下模板来提 issue,并打上 label，真心感谢~~~
## 我的问题

刚看了下实例，是用js render的，请问如何在react中使用呢？
## 我的期望

...

**Comment by jaredleechn** [comment]
在 componentDidMount 里面初始化 chart，绑定到 render 里面的 id

**Comment by zhuqiuyang** [comment]
@jaredleechn 谢谢 我试一下。

**Comment by zhuqiuyang** [comment]
@jaredleechn 能再详细或者给个example嘛 还是有点不明白。

**Comment by zhuqiuyang** [comment]
就是初始化ok后  render到组件里呢。

**Comment by zhuqiuyang** [comment]
是不是 

```
var chart = new G2.Chart({
  id: 'c1',
  width: 1000,
  height: 500,
  plotCfg: {
    margin: [10, 20, 10, 20],
  }
});
```

中的id属性和React组件中容器id对应起来。

**Comment by jaredleechn** [comment]
```
render() {
  return <div id="placeHolderForChart" />
},
componentDidMount() {
  const chart = new G2.chart({
    id: 'placeHolderForChart'
  });
}
```

**Comment by zhuqiuyang** [comment]
搞定了 谢谢~

**Comment by jaredleechn** [comment]
@zhuqiuyang 

💥 g2-react bump, see:
- homepage: https://github.com/antvis/g2-react
- doc: https://antvis.github.io/g2-react/
