### ISSUE TITLE
有  legend 事件的 API  吗

### ISSUE THREAD

**Issue by xream** [antvis/feedback#51]
如果是 G2 的使用问题，请您按照下面的模板来提 issue，并打上 label，真心感谢~~~
## 数据以及出现问题的源代码

``` js
  // ...
```
## G2 的版本以及使用环境
- G2 版本： 1.2.0
- 使用环境： Mac OS X, Chrome 40...

如果是其他的问题，请按照如下模板来提 issue,并打上 label，真心感谢~~~
## 我的问题

...
## 我的期望

...

**Comment by dxq613** [comment]
https://g2.alipay.com/api/#chart-legend-cfg

**Comment by xream** [comment]
@dxq613 抱歉 我之前的描述错误. 我是指相关事件, 目前只看到图表元素/坐标系内有事件.

**Comment by dxq613** [comment]
legend的相关事件没有放出来，仅仅在图表内使用，用于图例过滤数据。

**Comment by dxq613** [comment]
这个的事件其实也就2个 itemchecked, itemunchecked，你想监听这个两个事件有什么用么？如果在chart层次抛出来，也就是legendchange事件

**Comment by xream** [comment]
@dxq613 具体的需求是要控制和获取 legend 中 items 选中的状态.

**Comment by dxq613** [comment]
chart.filter('dim',arr)函数可以控制items的选中状态
过滤的对象存储在chart.get('filters')对象内，
但是具体的事件没有开放出来
