### ISSUE TITLE
'dodge'的具体格式？

### ISSUE THREAD

**Issue by maoyr** [antvis/feedback#53]
## 我的问题

我想实现一个分组柱状图，但是不了解'dodge'具体是种什么格式的数据，想看给出的参考代码中的data.json，不知道去哪里可以看一下具体的数据？
目前我的代码报错：Uncaught Error: dodge is not support linear attribute, please use category attribute!
参考代码：
 <script>
      $.getJSON('/data.json?filename=diamond',function (data) {
        var Stat = G2.Stat;
        var chart = new G2.Chart({
          id: 'c1',
          width: 1000,
          height: 500
        });
        // 配置列定义,设置y轴的最小值
        var colDefs = {
          price: {
            min: 0
          }
        };
        chart.source(data, colDefs);
        chart.intervalDodge().position(Stat.summary.mean('cut*price')).color('color');
        chart.render();
      });
    </script>
## 我的期望

想看给出的分组柱状图参考代码中的data.json，更多了解'dodge'的具体格式，谢谢！

**Comment by maoyr** [comment]
不好意思，刚刚才发现之前有答过相同的问题，已经知道data去哪里看了。用github不太熟，不知道怎么删掉自己的提问···

**Comment by okfine17** [comment]
what is the result?
