### ISSUE TITLE
使用GMap插件时有死循环。

### ISSUE THREAD

**Issue by Ah-Meow** [antvis/feedback#55]
如果是 G2 的使用问题，请您按照下面的模板来提 issue，并打上 label，真心感谢~~~
## 下面网页中复制粘贴来的代码

``` js
  // https://g2.alipay.com/demo/10-map/map-with-bubble.html
```
## G2 的版本以及使用环境
- G2 版本： 1.2.5
- 使用环境：Windows 10, Edge 25, Chrome 51, Firefox 46

**Comment by dxq613** [comment]
@simaQ 看看什么问题

**Comment by dxq613** [comment]
能把问题描述的更加清晰点么，怎么死循环？
