### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by tindytian** [antvis/feedback#56]
- G2 版本： 1.2.5
- 使用环境： Windows 10, Chrome 52...
## 我的问题
1. 能否为 axis 和 legend 设置额外的标题，如中文
2. 能否给 chart 设置标题
   ...
## 我的期望

...

**Comment by tindytian** [comment]
在文档中找到了column alias

``` js
 const colDefs = {
            type: {
                alias: 'xxxx',
                min: 0
            },
        };
```

chart 的标题估计设计的时候就让开发者在dom中设置

close

**Comment by simaQ** [comment]
恩，chart 的标题是需要由开发者自己设计的。
