### ISSUE TITLE
看了下示例，X轴坐标竟然不是从0开始的？

### ISSUE THREAD

**Issue by wxxcarl** [antvis/feedback#6]
X轴坐标竟然不是从0开始的，感觉看起来非常不习惯啊，像这个例子：
![image](https://cloud.githubusercontent.com/assets/3860334/15380848/ac424fc4-1dac-11e6-90c2-39e5ffddc2aa.png)
正常人看了都会觉得“付款”数量是0吧？

**Comment by simaQ** [comment]
可以进行列定义配置，执行 min 为 0

**Comment by dxq613** [comment]
列定义：

```
var defs = {
  a: {min: 0}
};

chart.source(data,defs);
```

详情参考： https://g2.alipay.com/tutorial/scale.html
