### ISSUE TITLE
如何单独调整图例宽度

### ISSUE THREAD

**Issue by Jane8Yu** [antvis/feedback#62]
## 显示不出完整legend

![qq 20160810164109](https://cloud.githubusercontent.com/assets/5189867/17547346/44dbc10e-5f19-11e6-90aa-1e8609f93db0.png)

legend太多的时候， 只显示部分legend。
chart.get('frontCanvas')貌似无法调整画布宽度。
就算 调整chart宽度也只是图标和图例按比例放宽，无法单独调整图例宽度。。

**Comment by dxq613** [comment]
可以设置边框

``` js
new Chart(
 plotCfg: {
  margin: [top,left,bottom,right]
}
);
```

也可以调整图例位置

chart.legend({position: 'bottom'})

**Comment by Jane8Yu** [comment]
## 1.

chart.legend({position: 'bottom'}) 即使放在底部仍然显示不完整。。

## 2.

new Chart(
 plotCfg: {
  margin: [top,left,bottom,right]
}
);
- margin参数应该是[top,right,bottom,left] 逆时针顺序。。
- 即使设置这个参数，图表会变形，难道就没有单独设置图例的长宽位置吗
