### ISSUE TITLE
如何获取地图上的坐标

### ISSUE THREAD

**Issue by Jane8Yu** [antvis/feedback#63]
chart.point().position(Stat.map.location('long*lant'));
var point = chart.getPosition({lant: lant,long: long});
这样写貌似不行啊

**Comment by TomHuangCN** [comment]
1. 

```
chart.getPosition({
   '..lant': lant,
   '..long': long
});
```
1. 这个API需要放在在chart.render()之后

**Comment by Jane8Yu** [comment]
谢谢，这个参数文档里没有，以后只能看g2源码吗 ？~~~~(>_<)~~~~

**Comment by dxq613** [comment]
是我们的文档没讲清楚，后面肯定会在文档中写清楚的，这些都属于统计函数转换出来的字段。
