### ISSUE TITLE
图表的宽度和高度不能自适应

### ISSUE THREAD

**Issue by enet2006** [antvis/feedback#68]
var chart = new G2.Chart({
  id: 'c1',
  width : 800,//希望不定义能默认100%
  height : 400//希望不定义能默认100%
});

**Comment by TomHuangCN** [comment]
高度无法自适应，宽度可配置，forceFit
![image](https://cloud.githubusercontent.com/assets/6113694/17917376/73eeb2fa-69ee-11e6-93f5-5ffb77429222.png)
