### ISSUE TITLE
柱状图第一个点有时会压在Y轴上

### ISSUE THREAD

**Issue by merfais** [antvis/feedback#69]
## 数据以及出现问题的源代码

![default](https://cloud.githubusercontent.com/assets/18030318/17968794/49b736d8-6b01-11e6-8c9d-d71cdaf3f213.png)
## G2 的版本以及使用环境
- G2 版本： 1.2.6
- 使用环境：Chrome
## 我的问题

对于柱状图，当X轴type不是cat类型时，坐标点不能很好的适配，如图，
x轴是时间，实际数据是15:00-15:59,第一个点出现在Y轴，最后自动补了一个点，没有压到Y轴。
这在其他类型图里没有什么大碍，如line，但在柱状图，气泡图这种本身需要宽度的，如果数据压到Y轴就显得太怪了。
我测试过其他的时间数据，X轴是做了自动计算并扩充数据的，但算法显然不是很智能，有时只是扩充了尾值，首值却没有处理。
## 我的期望

对于本身自带宽度属性（柱状图，气泡图等）的图，在计算坐标轴起始位置时，根据起止点与Y的距离和起止点自身的宽度进行适配，补充1~2点，不至于压到Y轴上。（需要负向坐标的除外）。

**Comment by dxq613** [comment]
问题并不是出在x轴的坐标自动计算上，而在于x轴的数值类型影响坐标轴坐标点的分布
- 连续类型的数据，第一个坐标点是从坐标轴的开始位置开始的
- 分类类型的数据，第一个坐标点不是从坐标轴的开始位置开始的,而是每个分类有一个范围

![image](https://cloud.githubusercontent.com/assets/1264678/18073262/1ffa750a-6e97-11e6-8f09-0f1ac1656448.png)

而柱状图本质是上是表现分类数据的大小对比，时间类型是连续类型，往往用于折线图之类表示趋势的图表，此时如果留下一段空白，对于折线图来说效果是很差的。

G2除了time类型外，还支持 timeCat的类型，如果你想在时间类型上展示柱状图的话，将数据类型改成timeCat即可：

```
var defs = {
  time: {type: 'timeCat'}
}
```

**Comment by merfais** [comment]
明白。谢谢。
希望在提供参数

```
var defs = {
  time: { 
    nice: true,
    type: 'time'
  }
}
```

的时候考虑一下 柱状图，气泡图这种本身需要宽度的坐标刻度的优化，
毕竟还是写了nice这个算法，用于变更数据的最小值、最大值，使得每个 tick 都是用户易于理解的数据，
那么， 还是希望在变更最小值的时候扩充一个刻度出来，谢谢

**Comment by dxq613** [comment]
时间的nice:true，不一定会对最小值进行扩展，这个问题的关键点其实在于，图表中的图形能够占用对应坐标轴的范围，默认情况下直角坐标系是 0-1，你可以调整这个参数，例如 0.1-0.9，那么坐标轴的两端就会有剩余空间

var defs = {
  time: { 
    type: 'time',
   range: [0.1,0.9]
  }
}
