### ISSUE TITLE
点击图表事件怎么支持？

### ISSUE THREAD

**Issue by zhujz** [antvis/feedback#7]
如果是 G2 的使用问题，请您按照下面的模板来提 issue，并打上 label，真心感谢~~~
## 数据以及出现问题的源代码

``` js
  // ...
```
## G2 的版本以及使用环境
- G2 版本： 1.2.0
- 使用环境： Mac OS X, Chrome 40...

如果是其他的问题，请按照如下模板来提 issue,并打上 label，真心感谢~~~
## 我的问题

点击图表事件怎么支持？
## 我的期望

咋获取到点击的x、y值

**Comment by dxq613** [comment]
demo忘记放出来了

```
chart.on('plotclick',funtion(ev){console.log(ev)});
```

**Comment by zhujz** [comment]
谢谢~
