### ISSUE TITLE
你好，有办法支持柱形图的顶部一致显示数据吗

### ISSUE THREAD

**Issue by zengAlex** [antvis/feedback#72]
如果是 G2 的使用问题，请您按照下面的模板来提 issue，并打上 label，真心感谢~~~
## 数据以及出现问题的源代码

``` js
  // ...
```
## G2 的版本以及使用环境
- G2 版本： 1.2.0
- 使用环境： Mac OS X, Chrome 40...

如果是其他的问题，请按照如下模板来提 issue,并打上 label，真心感谢~~~
## 我的问题

在使用的过程如何支持数据一直显示在柱形图的顶端尼`
...
## 我的期望

就像这样
![j 3b306 5w1w n63fc fj](https://cloud.githubusercontent.com/assets/13888110/18158563/ac94c860-7056-11e6-9b5b-de8f0a872360.png)

...

**Comment by zengAlex** [comment]
![j 3b306 5w1w n63fc fj](https://cloud.githubusercontent.com/assets/13888110/18158554/90bca52c-7056-11e6-8df3-c14879794061.png)

**Comment by simaQ** [comment]
使用 `label(dim, cfg)` 即可。
![image](https://cloud.githubusercontent.com/assets/6628666/18159366/cf9ba8b6-705a-11e6-9466-3897efbcef3c.png)

https://g2.alipay.com/api/geom.html#label

**Comment by zengAlex** [comment]
非常感谢，可以了

**Comment by simaQ** [comment]
不客气。
