### ISSUE TITLE
[Bug]箱线图的5个数有问题

### ISSUE THREAD

**Issue by alvin969** [antvis/feedback#73]
## 我的问题

按照[箱线图介绍](https://antv.alipay.com/chart/details/boxplot.html)，箱线图上的5个值分别是：
最大值、最小值、中位数、下四分位数及上四分位数，但是在实际的箱线图Demo中，tooltips的值在数据集里根本找不到，总有一些偏差。
## 我的期望

5个值能够采用数据集里的真实值。

**Comment by dxq613** [comment]
给出你的数据data，来看一看。

现在demo里面的数据的5个值都是通过统计函数计算出来的，当然你也可以在自己的数据源里面指定，有两种方式：
- 每个值是一个字段

```
var data = [{name: 'a', 'min': 10, 'quarter': 12, 'half': 15, threeQuarter: 20, max: 25}....]

chart.schema().position('name*(min+quarter+half+threeQuarter+max)').color('name').shape('box')
```
- 所有的值放到一个数组中

```
var data = [{name: 'a',value: [10,12,15,20,25]}...]
chart.schema().position('name*value').color('name').shape('box')
```
