### ISSUE TITLE
文字放置在圆环中心

### ISSUE THREAD

**Issue by zengAlex** [antvis/feedback#74]
如果是 G2 的使用问题，请您按照下面的模板来提 issue，并打上 label，真心感谢~~~
## 数据以及出现问题的源代码

``` js
  // ...
```
## G2 的版本以及使用环境
- G2 版本： 1.2.0
- 使用环境： Mac OS X, Chrome 40...

如果是其他的问题，请按照如下模板来提 issue,并打上 label，真心感谢~~~
## 我的问题

1.你好，请问我要怎么才能把文字放到使圆环中心尼？
例如这个
![lttp nlyf9wapu2 w6 o](https://cloud.githubusercontent.com/assets/13888110/18166547/62d048da-707e-11e6-90e5-3d9240d28a31.png)

2还有问一点，怎让绘制的图形居中显示？我就看到让文本居中的...
...
## 我的期望

...

**Comment by TomHuangCN** [comment]
暂时没有很友好的方式，试试这个。

```
chart.get('geoms')[0].get('coord').get('center');
```

**Comment by zengAlex** [comment]
好的，我试试，谢谢

**Comment by zachshelter** [comment]
今天我也在搜解决方案，发现使用guide()做比较好，定位准，也会自适应：    

chart.guide().tag([0, 0], [0.85, 0.50], `${count}`, {
      line: { lineWidth: 0 },
      text: { textAlign: 'center', fill: '#666', fontWeight: 'bold', fontSize: 24 },
      rect: { opacity: 0 }
    });
    chart.guide().tag([0, 0], [0.85, 0.30], `${title}`, {
      line: { lineWidth: 0 },
      text: { textAlign: 'center', fill: '#999' },
      rect: { opacity: 0 }
    });
