### ISSUE TITLE
G2，把绘的柱形图合并成一条

### ISSUE THREAD

**Issue by zengAlex** [antvis/feedback#75]
如果是 G2 的使用问题，请您按照下面的模板来提 issue，并打上 label，真心感谢~~~
## 数据以及出现问题的源代码

``` js
  // ...
```
## G2 的版本以及使用环境
- G2 版本： 1.2.0
- 使用环境： Mac OS X, Chrome 40...

如果是其他的问题，请按照如下模板来提 issue,并打上 label，真心感谢~~~
## 我的问题

我想要把柱形图合并成一条，
如下图，把这几个绘制出来的合并成一条，要怎么实现尼？
![l 9 74 i d x osi i1vit](https://cloud.githubusercontent.com/assets/13888110/18239691/810b7664-7379-11e6-9e8c-af1d5533401f.png)

...
## 我的期望

...

**Comment by TomHuangCN** [comment]
https://g2.alipay.com/demo/04-column/column-stack.html

你是指层叠柱状图？

**Comment by zengAlex** [comment]
打不开...

**Comment by simaQ** [comment]
层叠柱状图， https://antvis.github.io/G2-demo/examples/bar/column-stack.html

**Comment by zengAlex** [comment]
thanks
