### ISSUE TITLE
添加截图功能

### ISSUE THREAD

**Issue by hiduoshao** [antvis/feedback#76]
如果是 G2 的使用问题，请您按照下面的模板来提 issue，并打上 label，真心感谢~~~
## 我的需求/我的问题

我想请问一下，能否添加一个截图功能，点击某个图标就下载当前图标？

因为demo上的移植好麻烦，所以麻烦了。
## 数据以及出现问题的源代码

``` js
  // ...
```
## G2 的版本以及使用环境
- G2 版本： 1.2.0
- 使用环境： Mac OS X, Chrome 40...

如果是其他的问题，请按照如下模板来提 issue,并打上 label，真心感谢~~~
## 我的问题

...
## 我的期望

...

**Comment by dxq613** [comment]
后面增加接口

**Comment by dxq613** [comment]
已经增加，下个版本发布，2.2.0
