### ISSUE TITLE
g2-mobile

### ISSUE THREAD

**Issue by zengAlex** [antvis/feedback#78]
如果是 G2 的使用问题，请您按照下面的模板来提 issue，并打上 label，真心感谢~~~
## 数据以及出现问题的源代码

``` js
  // ...
```
## G2 的版本以及使用环境
- G2 版本： 1.2.0
- 使用环境： Mac OS X, Chrome 40...

如果是其他的问题，请按照如下模板来提 issue,并打上 label，真心感谢~~~
## 我的问题

g2-mobile  是不是不能支持跟pc 同样的API。
例如这个：
chart.intervalStack().position('month*tem').label('tem');

...
## 我的期望

...

**Comment by dxq613** [comment]
为了防止代码大小膨胀，去除了很多功能，但是核心语法保持一致：

你这个语句中 label 方法不支持

**Comment by zengAlex** [comment]
好的，谢谢

**Comment by TomHuangCN** [comment]
发了2.0.1。已经解决了

**Comment by TomHuangCN** [comment]
fix
