### ISSUE TITLE
绘制有误

### ISSUE THREAD

**Issue by zengAlex** [antvis/feedback#79]
如果是 G2 的使用问题，请您按照下面的模板来提 issue，并打上 label，真心感谢~~~
## 数据以及出现问题的源代码

``` js
  // ...
```
## G2 的版本以及使用环境
- G2 版本： 1.2.0
- 使用环境： Mac OS X, Chrome 40...

如果是其他的问题，请按照如下模板来提 issue,并打上 label，真心感谢~~~
## 我的问题

请问，为什么渲染不会按照值的绘制图形越大？反而变小了...

![nu12s_ chhcsl7xgb g nc](https://cloud.githubusercontent.com/assets/13888110/18348585/c1ff4c9a-75fe-11e6-9d99-652002885fc8.png)

...
## 我的期望

...

**Comment by dxq613** [comment]
把你的data 和语法列出来
