### ISSUE TITLE
地图类图表使用

### ISSUE THREAD

**Issue by Alpha-liu** [antvis/feedback#8]
## 地图引用

帮忙说明下如何在本地使用下面链接里的地图。
https://g2.alipay.com/demo/10-map/world-map.html

对这段里的调用不是太理解。data.json?filename=world.geo是否是标准文件还是要自己定义？如果是标准文件请分享；如果要自制，麻烦提供格式。
$.getJSON('/data.json?filename=world.geo', function(mapData) {

**Comment by dxq613** [comment]
标准geojson，有相应的规范:http://geojson.org/
demo中的文件，自己复制一下链接，下载一下好了，后面我把这些数据放到github上

**Comment by dxq613** [comment]
在新的库里面增加了
https://github.com/antvis/resource/tree/master/geo

**Comment by Alpha-liu** [comment]
多谢！
