### ISSUE TITLE
如何在柱状图上标记数值

### ISSUE THREAD

**Issue by wangjinghui-cn** [antvis/feedback#81]
如果是 G2 的使用问题，请您按照下面的模板来提 issue，并打上 label，真心感谢~~~
## 我的需求

在柱状图上标记数值
## 我的问题

我们有需求是在柱状图上标注数值，文档内没有看到相关介绍
![image](https://cloud.githubusercontent.com/assets/18734995/18499492/0e285310-7a72-11e6-9674-c20101179568.png)

**Comment by dxq613** [comment]
标注数字，有两种方式：
- 使用label语法
  
  ```
  chart.interval().position('x*y').label('y');
  ```
- 使用guide 语法

https://g2.alipay.com/tutorial/guide.html#辅助标记
