### ISSUE TITLE
使用html模板自定义了tooltip后，画布边界的tooltip显示会越界变形（不能像默认的tooltip自动显示到可视区域）

### ISSUE THREAD

**Issue by francis-su** [antvis/feedback#82]
## 我的需求/我的问题

如题，使用教程里推荐的html模板自定义了tooltip,画布边界的tooltip显示会越界（不能像默认的tooltip自动显示到可视区域）,请看以下截屏或者也可看官网上那个[自定义tooltip  html 模板示例](https://g2.alipay.com/tutorial/tooltip.html)

![screen shot 2016-09-14 at 00 49 03](https://cloud.githubusercontent.com/assets/8065706/18614975/55083e14-7dcc-11e6-9ac7-455406cfae7a.png)
## 数据以及出现问题的源代码

``` js
  chart.tooltip(true, {
            custom: true, // 表示使用自定义的模板显示 tooltip
            html:  '<div class="chart-tooltip" style="position:absolute;visibility: hidden;"><span class="ac-title"></span>:00<table class="ac-list custom-table"></table></div>', // tooltip 的 html 外层模板
            itemTpl: '<tr><td>{index}</td><td>{name}:</td><td>{value}元</td></tr>', // 使用 html 时每一个显示项的模板，默认支持 index, color, name, value 这四个字段。
            offset: 50, // 偏移量，设置tooltip 显示位置距离 x 轴方向上的偏移
            //customFollow: false // 设置 tooltip 是否跟随鼠标移动，默认为 true，跟随。
        });
```
## G2 的版本以及使用环境
- G2 版本： 2.0.1
- 使用环境： Mac OS X, Chrome 53...
## 我的期望

使用html模板自定义的tooltip，在画布边界显示时能像默认的tooltip自动显示到可视区域

**Comment by simaQ** [comment]
你好，这个问题在 `2.0.3` 版本已经解决，

``` js
<script src="https://as.alipayobjects.com/g/datavis/g2/2.0.3/index.js"></script>
```
