### ISSUE TITLE
安卓部分浏览器无法显示图表

### ISSUE THREAD

**Issue by arronf2e** [antvis/feedback#83]
如果是 G2 的使用问题，请您按照下面的模板来提 issue，并打上 label，真心感谢~~~
## 数据以及出现问题的源代码

``` js
  // ...
```
## G2 的版本以及使用环境
- G2 版本： 1.2.0
- 使用环境： Mac OS X, Chrome 40...

如果是其他的问题，请按照如下模板来提 issue,并打上 label，真心感谢~~~
## 我的问题

...
## 我的期望

...

**Comment by dxq613** [comment]
移动端有单独的g2-mobile，https://g2.alipay.com/mobile-demo/
