### ISSUE TITLE
动态数据如何实时更新？

### ISSUE THREAD

**Issue by kchjxxgh** [antvis/feedback#84]
## 我的需求/我的问题

在所有的文档中，没有找到如何实时更新chart？看到antv里面有提到实时更新，但是没有具体说明。（https://antv.alipay.com/design/rule/func/liveupdate.html）。
比如EChart就说自己是数据驱动，可以动态更新。请问G2该如何动态更新数据呢？如果暂时不支持，是否有支持计划？如果支持，能否给个例子，或者把这个例子加到帮助文档中。
## 数据以及出现问题的源代码

``` js
  // ...
```
## G2 的版本以及使用环境
- G2 版本： 2.0
- 使用环境： Mac OS X, Chrome 40...

**Comment by simaQ** [comment]
chart.changeData(data) 详见 https://g2.alipay.com/api/index.html#changedata

**Comment by kchjxxgh** [comment]
非常感谢，已经用上了。但是，变化的非常生硬，没有动画效果，现在不支持补间动画么？animate是默认的true，还是需要额外设什么？

**Comment by simaQ** [comment]
目前 changeData 的时候是没有动画的，目前版本还不支持，但是动画这块我们已经在开发优化了，差不多月底的样子会发布 2.1 版本，优化动画效果并添加补间动画。
