### ISSUE TITLE
legend 设置word的font-size属性，取消选中后font-size失效

### ISSUE THREAD

**Issue by merfais** [antvis/feedback#86]
如果是 G2 的使用问题，请您按照下面的模板来提 issue，并打上 label，真心感谢~~~
## 数据以及出现问题的源代码

``` js
  // https://g2.alipay.com/demo/05-pie/pie.html
  chart.legend('name', {
        position: 'bottom',
        word: {
        'font-size': '24px',   //  需求并不是24，为了测试，显示的明显些
          fill: '#000'
        }
      });
```

![123](https://cloud.githubusercontent.com/assets/18030318/19436258/a2cdda32-94a1-11e6-9111-c392c9bc6d4d.png)
## G2 的版本以及使用环境
- G2 版本： 2.0.4
- 使用环境：windows, Chrome
## 我的问题

怎么设置图例字体在取消选中状态时的字号，
需求来源于，由于legend的太多，空间又比较小，想通过改变字体和间距来放下多一些的图例。
但在取消选中状态时，字号又变了回去，
## 我的期望

求参数

**Comment by simaQ** [comment]
如果图例太多，可以设置自动换行

```
chart.legend('name', {
  itemWrap: true
})
```

**Comment by merfais** [comment]
不是换行的问题，是font-size失效，
换行确实能解决一部分图例多问题，但如果给定的绘图区域比较小的时候，为了压缩图例的占比，确实需要使图例小一些，
plotcfg.margin，dy,dx,spacingX,spacingY都有用到就是为了在小的区域显示尽可能多的图例。
如果font-size不失效的话，效果会更好一些。
然而font-size 在取消选中状态时，恢复了默认的字号，导致样式出问题。

**Comment by simaQ** [comment]
``` js
chart.legend('continent', {
  word: {
    fill: 'red',
    'font-size': 18 // 传递数字
   } 
});
```

**Comment by merfais** [comment]
难道是用的版本有问题吗
https://g2.alipay.com/demo/05-pie/pie.html
拜托在你们的官网上测试一下好不好，
传递数组如果管用的话，。。。。。。。。。
数字，字符串，我已测过多次，我还以为你们更新了官网的实例，我又测了一次，无效！！！！！

**Comment by simaQ** [comment]
1. 您好，我是在官网上测试的，是生效的；
2. 您的浏览器是 chrome ，您的字体小于 12px ，Chrome 浏览器在解析字体大小时，最小字号为12px，小于这个大小的字号都会解析成12px。

**Comment by TomHuangCN** [comment]
这个问题，本周已经修复了，忘记回复你了，不好意思！@merfais

**Comment by TomHuangCN** [comment]
急的话，可使用2.0.5-beta。正式版下周发 @merfais

**Comment by merfais** [comment]
font-size有效了，
但是
指定font-size后。legend 文字的 hover click 都失效了，只用 legend 的marker 的 hover和click 有效
