### ISSUE TITLE
饼图tooltip显示错误

### ISSUE THREAD

**Issue by merfais** [antvis/feedback#87]
## 数据以及出现问题的源代码

``` js
  // https://g2.alipay.com/demo/05-pie/pie.html
 var data = [
        {name: 'Microsoft Internet Explorer', value: 56 },
        {name: 'Chrome', value: 56},
      ];
```

![123](https://cloud.githubusercontent.com/assets/18030318/19436738/85df3e68-94a4-11e6-9290-ce35a311d2ef.png)
![234](https://cloud.githubusercontent.com/assets/18030318/19436739/8603c63e-94a4-11e6-92aa-60af73ccee95.png)
## G2 的版本以及使用环境
- G2 版本： 2.0.4
- 使用环境：windows Chrome.
## 我的问题

当只有两条数据，且值相同时，tooltip并不会change
## 我的期望

...

**Comment by simaQ** [comment]
这个是我们的bug，这周解决~

**Comment by simaQ** [comment]
请使用 2.0.5 及以上版本。
