### ISSUE TITLE
不是问题

### ISSUE THREAD

**Issue by cnukaus** [antvis/feedback#88]
看到你们的规范，很有收获，觉得中国是需要自己的可视化规范，多谢！

如果是 G2 的使用问题，请您按照下面的模板来提 issue，并打上 label，真心感谢~~~
## 数据以及出现问题的源代码

``` js
  // ...
```
## G2 的版本以及使用环境
- G2 版本： 1.2.0
- 使用环境： Mac OS X, Chrome 40...

如果是其他的问题，请按照如下模板来提 issue,并打上 label，真心感谢~~~
## 我的问题

...
## 我的期望

...

**Comment by dxq613** [comment]
多谢，后续有更多惊喜。我们希望能够用一套语法，实现所有的可视化图表。
