### ISSUE TITLE
安卓手机vivo Xplay5A、锤子 sm801图表初始加载时出现黑色背景，图表上面的字和线颜色正常

### ISSUE THREAD

**Issue by xinnai** [antvis/feedback#89]
如果是 G2 的使用问题，请您按照下面的模板来提 issue，并打上 label，真心感谢~~~
## 数据以及出现问题的源代码

``` js
  http://gitlab.alibaba-inc.com/alijk/alihealth-h5/blob/master/static/src/care_plan/components/PieChart.js
http://gitlab.alibaba-inc.com/alijk/alihealth-h5/blob/master/static/src/care_plan/components/BloodPressureChart.js
```
## G2 的版本以及使用环境

-"g2": "^1.2.7",
    "g2-react": "^1.1.0",
- 使用环境：vivo Xplay5A
  Android: 5.1.1

如果是其他的问题，请按照如下模板来提 issue,并打上 label，真心感谢~~~
## 我的问题

如何解决安卓图表黑屏的问题
...
## 我的期望

...
![_20161029_175648](https://cloud.githubusercontent.com/assets/23135336/19828832/7f392f48-9e03-11e6-98fd-65cabf35b483.jpg)
![_20161029_175639](https://cloud.githubusercontent.com/assets/23135336/19828831/7e9266cc-9e03-11e6-9b6d-f11c0da8a409.jpg)
![_20161029_175237](https://cloud.githubusercontent.com/assets/23135336/19828830/7e6b6aae-9e03-11e6-9391-a06018034f00.jpg)

**Comment by dxq613** [comment]
移动端建议使用 g2-mobile,g2不是为移动端设计的，没有对所有的手机进行检测，性能也不好。

https://g2.alipay.com/mobile-demo/
