### ISSUE TITLE
如何获取toolip上的值，以及鼠标移动得到当前点的坐标？

### ISSUE THREAD

**Issue by kcl2430** [antvis/feedback#9]
如果是 G2 的使用问题，请您按照下面的模板来提 issue，并打上 label，真心感谢~~~
## 我的需求/我的问题

如何获取toolip上的值，以及鼠标移动得到当前点的坐标？
## 我的期望

实现这种效果
![qq 20160519155508](https://cloud.githubusercontent.com/assets/14937225/15387038/67fecdb6-1ddd-11e6-8529-d2094ad73b96.png)

**Comment by simaQ** [comment]
### plotmove(ev)

鼠标在坐标系内移动时触发，在图表的坐标系外不触发。

`ev` 表示事件触发时返回的对象。

``` js
chart.on('plotmove', function(ev) {
  var point = {
    x: ev.x,
    y: ev.y
  };
  var items = chart.getTooltipItems(point);  // 获取tooltip的值
  console.log(items);
});
```

关于事件的 API 本周会补充到网站。

**Comment by kcl2430** [comment]
非常的感谢您的回复，，我想问问如果采用g2可以实现我上面那张图的效果吗？？

**Comment by kcl2430** [comment]
还有像这种getTooltipItems函数，我怎么找到？？？

**Comment by simaQ** [comment]
股票图的demo： https://g2.alipay.com/demo/06-k/k-chart.html
可以实现的，不过这种还需要你自己做一些实现。
![image](https://cloud.githubusercontent.com/assets/6628666/15387344/3b51610a-1ddf-11e6-937a-1f52edd3d311.png)
![image](https://cloud.githubusercontent.com/assets/6628666/15387349/410e150c-1ddf-11e6-9746-39bc1f097096.png)

我正在完善 api 中，本周会更新上去的 😄

**Comment by kcl2430** [comment]
非常的感谢

**Comment by kcl2430** [comment]
![image](https://cloud.githubusercontent.com/assets/14937225/15389053/866a22be-1de7-11e6-9736-554f7477f755.png)
chart.on('plotmove', function(ev) {
            var point = {
                x: ev.x,
                y: ev.y
            };
            var items = chart.getTooltipItems(point);  // 获取tooltip的值
            chart.guide().tag([tmpData[0].time, items[0].value],[tmpData[tmpData.length-1].time, items[0].value],'价格均值');
            chart.repaint();
        });
如何实时更新他的画布，不影响以前的，我用chart.repaint();这个怎么没有用啊？？

**Comment by simaQ** [comment]
chart.guide() 在我们的语法里面是属于辅助元素，用于静态的展示。其实你这个需求是另一种形式的 tooltip，目前我们的 tooltip 还只要一种形式。

这个你也可以用 dom 来实现，chart.getPosition({xDim: value, yDim: value}) 可以获取数据对应在画布空间的坐标，得到画布坐标之后你就可以直接插入你的 dom 元素了。

**Comment by kcl2430** [comment]
g2不是采用canvas画的吗，，不是直接在画布上画吗？？

**Comment by simaQ** [comment]
是的呢，但是 guide() 我们只是用于静态展示的，目前这种 tooltip 的展示方式还不支持，但是提供了接口供用户用其他方法实现，后续我们会考虑增加这种的。

**Comment by kcl2430** [comment]
非常感谢

**Comment by kcl2430** [comment]
我想要在g2上画虚线，那如何获取到g2的画布呢，，因为如果我自己创建画布的话就会把g2的画布给覆盖掉，还有您前面提到采用dom实现，g2采用的是canvas，canvas怎么能插入dom,不是直接在上面画图的吗？

**Comment by simaQ** [comment]
用 css 样式来控制 dom 位置，而不是 canvas 中插入。

G2 的图表由三层 canvas 组成:
- 最上层画布 chart.get('frontCanvas') 用于绘制 tooltip guide 和 图例（legend）
- 中间画布 chart.get('canvas') 用于绘制 geom（图形对象）
- 最下面 chart.get('backCanvas') 用于绘制坐标轴 axis

**Comment by kcl2430** [comment]
谢谢您的回答
