### ISSUE TITLE
G2 能否动态插入数据？

### ISSUE THREAD

**Issue by zachshelter** [antvis/feedback#90]
## 我的问题

我们开发过程中希望能够每隔一定时间插入一条数据，并在图表中显示，但是看了目前的API并没有一个很好的方法

## 我的期望

能够有一个API可以实现插入新的数据，并且动画效果能够感觉是直接插入，而不是重新渲染一次。

非常感谢。

**Comment by zachshelter** [comment]
晚上才看到正好更新了。

非常感谢

**Comment by simaQ** [comment]
哈哈
