### ISSUE TITLE
G2股票图使用问题

### ISSUE THREAD

**Issue by suer-react** [antvis/feedback#91]
＃G2股票图使用问题
一直报G2.Plugin.range is not a constructor(…)

＃源码：
   var Stat = G2.Stat;
        var chart = new G2.Chart({
          id: this.props.regressionId,
          width: 1000,
          height: 350,
          plotCfg: {
            margin: [30, 120, 30],
            background: {
              fill: '#191821'
            }
          }
        });
        // g-plugin-range 只支持数值类型的数据排序，所以将时间统一转换为时间戳
        for(var i=0;i<this.props.realtimeQuotes.length;i++) {
          var item = this.props.realtimeQuotes[i];
          var time = item.date;
          item.date = new Date(time).getTime();
        }
        // 创建数据源
        var Frame = G2.Frame;
        var frame = new Frame(formatChartData(this.props.realtimeQuotes) );
        frame.addCol('trend', function(obj) {
          return (obj.open <= obj.close) ? 0 : 1;
        });
        chart.source(frame, {
          'trend': {
            type: 'cat',
            alias: '趋势',
            values: ['上涨','下跌']
          },
          'date': {
            type: 'timeCat',
            nice: false,
            mask: 'yyyy-mm-dd',
            alias: '时间',
            tickCount: 10
          },
        'volume': {alias: '成交量'},
        'open': {alias: '开盘价'},
        'close': {alias: '收盘价'},
        'high': {alias: '最高价'},
        'low': {alias: '最低价'},
        'open+close+high+low': {alias: '股票价格'}
        });
        chart.axis('date', {
          title: null
        });
        chart.schema()
          .position('date*(open+close+high+low)')
          .color('trend', ['#2AF483','#F80041'])
          .shape('candle')
          .tooltip('open*close*high*low*volumn');
      

        var chart1 = new G2.Chart({
          id: this.props.regressionId,
          width: 1000,
          height: 150,
          plotCfg: {
            margin: [10, 120, 50],
            background: {
              fill: '#191821'
            }
          }
        });
        chart1.source(frame);
        chart1.col('volumn', {
          alias: '成交量(万)',
          tickCount: 2,
        });
        chart1.col('date',{
          type: 'timeCat',
          nice: false,
          mask: 'yyyy-mm-dd',
          alias: '时间',
          tickCount: 10
        });
        chart1.axis('date', false);
        chart1.interval()
          .position('date*volumn')
          .color('trend', ['#2AF483','#F80041'])
          .tooltip('volumn');
        chart1.legend('trend', false);
   
        var range = new G2.Plugin.range({
            id:  "range",
            width: 840,
            height: 26,
            dim: 'date'
        });
        range.source(frame);
        range.link([chart, chart1]);
        range.render();

## G2 的版本以及使用环境

- G2 版本： 1.2.5
- 使用环境： Mac OS X, Chrome 54

**Comment by simaQ** [comment]
你好，G2.Plugin.range 是滑块条，使用的话你需要在页面引入：

``` js
<!-- 引入 range 组件的 css 样式 -->
<link rel="stylesheet" type="text/css" href="https://os.alipayobjects.com/rmsportal/UBXCMkzNVlaZYNs.css">
<!-- 引入 range 组件脚本 -->
<script src="https://as.alipayobjects.com/g/datavis/g-plugin-range/0.0.9/index.js"></script>
```

如果你不需要，把这代码去了，然后调用 chart.render();

``` js
 var range = new G2.Plugin.range({
        id:  "range",
        width: 840,
        height: 26,
        dim: 'date'
    });
    range.source(frame);
    range.link([chart, chart1]);
    range.render();
```
