### ISSUE TITLE
[Scale] tick 不能均匀分布

### ISSUE THREAD

**Issue by bulletnoid** [antvis/feedback#92]
## 我的需求/我的问题
Scale 设为 timeCat, 指定 tickCount 时 tick 不能均匀分布
![test](https://cloud.githubusercontent.com/assets/2130336/20342086/fd3b90d8-ac23-11e6-8fb3-d8a90a284ba1.png)

## 数据以及出现问题的源代码
使用示例 https://g2.alipay.com/demo/03-area/area-percent.html
中在横轴上使用 timeCat
```js
chart.source(data, {
  year: {
    type: 'timeCat',
    mask: 'yyyy',
    tickCount: 5
  },
  '..percent': {
    formatter: function(value) {
      value = value || 0;
      value = value * 100;
      return parseInt(value);
    },
    alias: 'percent(%)'
  }
});
```

## G2 的版本以及使用环境

- G2 版本： 2.1.3
- 使用环境： any

## 我的问题

...

## 我的期望

...

**Comment by dxq613** [comment]
因为你的数值一共就6，7个控制显示5个，只能移除掉几个。。。这时候最后面就会出现不均匀

**Comment by dxq613** [comment]
没法做到精确的均匀，在新的版本里面做了一些优化。
