### ISSUE TITLE
[bug]快速上手例子显示错误

### ISSUE THREAD

**Issue by wengqianshan** [antvis/feedback#94]
## 官方例子显示错误

用快速开始的例子在本地试了一下也是错的，付款对应的数据100没有显示，试了将下单数据改成100同样无法显示

## 源码

```js
var data = [
  {action: '访问', visitor: 500},
  {action: '浏览', visitor: 400},
  {action: '交互', visitor: 300},
  {action: '下单', visitor: 200},
  {action: '付款', visitor: 100}
];
var chart = new G2.Chart({
  id: 'c1',
  width : 800,
  height : 400
}); // 创建图表
chart.source(data); // 载入数据源
chart.interval().position('action*visitor').color('action'); // 使用图形语法绘制柱状图
chart.render();
```

![image](https://cloud.githubusercontent.com/assets/854370/20473761/c0921340-affd-11e6-954e-eca6517476b4.png)

## G2 的版本以及使用环境

- G2 版本： 2.1.3
- 使用环境： macOS Sierra, Chrome 54

**Comment by simaQ** [comment]
不是没有显示，是因为我们默认提供的Y轴最小值不是从 0 开始的，而且取得Y轴对应属性的最小值，你可以通过列定义，将 Y 轴最小值手动设置为 0.

```
chart.source(data, {
  visitor: {
    min: 0
  }
});
```

**Comment by wengqianshan** [comment]
@simaQ 噢，之前没有注意到Y轴，不过我觉得是个问题，因为我把付款由100改为99，就可以显示了，你可以试下。

![image](https://cloud.githubusercontent.com/assets/854370/20512460/722330b4-b0ba-11e6-819a-25f88616473f.png)

**Comment by dxq613** [comment]
坐标轴会自动计算间隔个坐标点，然后对坐标点进行一些处理使得人看上去更舒服

如果原始的值是 100,200,300,400,500 那么计算出间隔是100，坐标点不会受影响

但是如果原始值是 99，199，299，499之类，会将变成 [0-500]

**Comment by dxq613** [comment]
如果你想关闭这个优化，可以使用 

```
var defs = {
  value: {nice: false}
};
chart.source(data,defs); 
```

就不会进行坐标点的优化了
