### ISSUE TITLE
AntV部分图无显示

### ISSUE THREAD

**Issue by 0xzkzhao** [antvis/feedback#96]
https://antv.alipay.com/chart/details/bar.html
![qq](https://cloud.githubusercontent.com/assets/2425141/20622529/4a4781fe-b33e-11e6-8c1d-2536f4edcc9d.png)

如图，最上面的图有，但是下面的都不显示了

**Comment by dxq613** [comment]
由于页面上图表比较多，所以图表使用了延迟加载的功能，有时候会加载不出来，后面改版的时候统一解决
