### ISSUE TITLE
请问如何调整波动幅度

### ISSUE THREAD

**Issue by junmaqiang** [antvis/feedback#97]
我想让左边数值（200-900）超过5的波动都能看到，
可是不晓得调整哪里

代码层面我猜应该调整下面的地方
`  chart.line().position('NEWDATE*value').size(2);
  chart.render();`

官方手册没有` position()` 这个方法的说明

还望知晓的朋友帮下忙好不好，非常感谢！

![ff2a8](https://cloud.githubusercontent.com/assets/1819457/20738591/3e5d795c-b6ef-11e6-99d1-0f73a0615b22.JPG)

**Comment by dxq613** [comment]
你可以设置y轴上数值的最小值

chart.col('value',{min: 700});

**Comment by dxq613** [comment]
你这个比较麻烦，因为两个数据集的数据差异比较大，所以单条数据的波动不明显，可以使用双轴的方式：

```js
chart.line().position('NEWDATE*value1').color('red'); 
chart.line().position('NEWDATE*value2').color('blue'); 
```

这时候，两个数据值个不干扰，波动就明显了

**Comment by junmaqiang** [comment]
谢谢你 dxq613
