### ISSUE TITLE
Guys, you doing great! 

### ISSUE THREAD

**Issue by fedorinoGore** [antvis/feedback#98]
I have no knowledge of Chinese language.
So just wanted to know - if any plans to localize rest of the docs to English?
I could see that UI components are already well documented.
So maybe you have similar plans for Ant V library?

如果是 G2 的使用问题，请您按照下面的模板来提 issue，并打上 label，真心感谢~~~

## 数据以及出现问题的源代码

```js
  // ...
```

## G2 的版本以及使用环境

- G2 版本： 1.2.0
- 使用环境： Mac OS X, Chrome 40...

如果是其他的问题，请按照如下模板来提 issue,并打上 label，真心感谢~~~

## 我的问题

...

## 我的期望

...

**Comment by dxq613** [comment]
I have written two simple documents, follow-up will be updated in the wiki, the English version of the site in the back to achieve。

guide: https://github.com/antvis/g2/wiki/How-to-create-a--chart
api: https://github.com/antvis/g2/wiki/API
